<style type="text/css">
tfoot input {
        width: 100%;
        padding: 1px;
        box-sizing: border-box;

    }

    thead{

      background-color: #000000;
      color:#fff;
      height: 2px !important;
    }
    #reporteador_length{
      margin-left: 300px;
    }
    #menu{

      width: 300px;
      height: 100px;
      background-color: black;
    }

    .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
          padding: 1px !important; 

    }
    div#<?php echo $this->grid;  ?>_filter.dataTables_filter{
   // display: none !important;
   background-color: #fff !important;
   color: #fff !important;
   z-index: -1!important;
   margin-top: -300px;
}
</style>
<script type="text/javascript">
      var Id;
    $(document).ready(function() {
      MostrarGrid(false);
     $("#msj-conf-datos-cliente").hide();
     $("#msj-conf-datos-cliente-actu").hide();
     $("#msj-conf-datos-dir-actu").hide();
     $("#msj-conf-datos-dir").hide();
     $("#msj-conf-datos-dir-pro").hide();
     $("#msj-conf-datos-prov-actu").hide();
     //ocultar boton de actualizar
     $("#aCliente").hide();
     $("#aClienteDir").hide();
     $("#aClientePro").hide();
     $("#aProveedorDir").hide();
     $("#"+sessionStorage.getItem("valor")+"l").addClass("active");
    function MostrarGrid(valor){
            $('#<?php echo $this->grid;  ?>').DataTable({
                    "ajax": {
                    "url": "<?php echo $this->urlGrid;?>?valor="+ sessionStorage.getItem("valor")
                },

                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "search": "",
                    "zeroRecords": "No existe el registro",
                    "info": "Página _PAGE_ de _PAGES_",
                    "infoEmpty": "No records available",
                    "infoFiltered": "(Encontrado de _MAX_ registros)",
                    "paginate": {
                        "first":      "Inicio",
                        "last":       "Último",
                        "next":       "Siguiente",
                        "previous":   "Anterior"
                    }
                },
                "lengthMenu": [[10, 20, -1], [10, 20, "Todo"]],

             dom: 'Blfrtip',
      buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ],
     "lengthMenu": [[10, 25, 50,100,200,500,1000 -1], [10, 25, 50,100,200,500,1000, "All"]]
       
            });

            var table = $('#<?php echo $this->grid;  ?>').DataTable();

            $('#<?php echo $this->grid;  ?> tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');

             Id = $(this).find('td').eq(0).html();
            $("#id").val(Id);
            OrdenID=$("#id").val();

       
            }

        });

        //editar
         $("#cancelar").click(function(){
            $('#<?php echo $this->nomForm;?>')[0].reset();
            window.location="<?php echo $this->baseUrl; ?>";
        });
    $("#editarCliente").click(function(){
           // alert(Id);
            $("#aCliente").show();
            $("#gCliente").hide();
            $("#aClienteDir").show();
            $("#gClienteDir").hide();
            $("#aClientePro").show();
            $("#gProveedor").hide();
            $("#gProveedorDir").hide();
            $("#aProveedorDir").show();
            //return false;
            if(Id != ""){

     $.post("<?php echo $this->consultaCliente; ?>",{idCliente:Id},
                function(data){
                  $("#id_cliente").val(data.datos[0].id_cliente);
                  $("#id_clienteDir").val(data.datos[0].id_cliente);
                  $("#id_ProvDir").val(data.datos[0].id_cliente);
                  $("#id_clienteProDir").val(data.datos[0].id_cliente);
                  
                  $("#idroveedor").val(data.datos[0].id_cliente);
                  $("#rcomercial").val(data.datos[0].rcomercial);
                  $("#rfc").val(data.datos[0].rfc);
                  $("#telefono").val(data.datos[0].telefono);
                  $("#pagweb").val(data.datos[0].pagweb);
                  $("#id_categoria").val(data.datos[0].id_categoria);
                  $("#id_estatus").val(data.datos[0].id_estatus);
                  $("#condpago").val(data.datos[0].condpago);
                  $("#diasrevision").val(data.datos[0].diasrevision);
                  $("#contacto1").val(data.datos[0].contacto1);
                  $("#mailcont1").val(data.datos[0].mailcont1);
                  $("#refcont1").val(data.datos[0].refcont1);
                  $("#contacto2").val(data.datos[0].contacto2);
                  $("#mailcont2").val(data.datos[0].mailcont2);
                  $("#refcont2").val(data.datos[0].refcont2);
                  $("#Contacto3").val(data.datos[0].contacto3);
                  $("#mailcont3").val(data.datos[0].mailcont3);
                  $("#refcont3").val(data.datos[0].refcont3);
                  $("#refcont3").val(data.datos[0].refcont3);
                  $("#id_vendedor").val(data.datos[0].id_vendedor);
                  
                  //consultar la dirección ligada al cliente
            $.post("<?php echo $this->consultaDireccion; ?>",{idCliente:Id},
                function(data){

                  $("#id_tipodireccion").val(data.datos[0].id_tipodireccion);
                  $("#estatusDir").val(data.datos[0].id_estatus);
                  $("#calle").val(data.datos[0].calle);
                  $("#colonia").val(data.datos[0].colonia);
                  $("#ciudad").val(data.datos[0].ciudad);
                  $("#municipio").val(data.datos[0].municipio);
                  $("#estado").val(data.datos[0].estado);
                  $("#cp").val(data.datos[0].cp);
                  $("#nota").val(data.datos[0].nota);


                },'json');

                  $("#btnNuevaOrden").trigger("click");
                },'json'

                );

              
            }
           

        });

      //boton de suspender
      $("#suspender").click(function(){

        alert("suspender a " + Id);

      });
        
    }




     $("#buscadorGeneral").change(function(){
        //alert("hola");
                 $("[aria-controls='<?php echo $this->grid; ?>']").val($("#buscadorGeneral").val());
                 $('#<?php echo $this->grid; ?>_filter input').attr("placeholder", "BUSCAR");
                 $('#<?php echo $this->grid; ?>_filter input').addClass("text-uppercase");
                 $('#<?php echo $this->grid; ?>_filter input').focus();
                });

     $(".pagination li a").click(function(){
             sessionStorage.setItem("valor", $(this).attr("id"));
             window.location='<?php echo $this->redireccionar; ?>';
            $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();

     });


     //funcionalidades para guardar
     $("#gCliente").click(function(){
      var clientes=$("#<?php echo $this->nomForm;?>").serialize();
       // alert(clientes);
       //return false;
      $.post("<?php echo $this->guardarCliente; ?>",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           $("#id_clienteDir").val(data.idCliente);
           $("#msj-conf-datos-cliente").show();
          // $('#myModal').modal('toggle');//cerramos el modal despues de agregar dirección
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
            
        },'json'

        );
   return false;

    });
     $("#gProveedor").click(function(){
      var clientes=$("#<?php echo $this->nomForm; ?>").serialize();
        //alert(clientes);
        //return false;
      $.post("<?php echo $this->guardarCliente; ?>",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
            $("#msj-conf-datos-cliente").show();
            $("#id_clienteProDir").val(data.proveedor);
           //$('#myModal').modal('toggle');
           //$('#<?php echo $this->nomForm; ?>')[0].reset();
            
        },'json'

        );

      return false;

    });
     $("#gClienteDir").click(function(){
      var clientes=$("#<?php echo $this->nomForm; ?>DirC").serialize();
       // alert(clientes);
        //return false;
      $.post("Clientes/guardardireccion",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           //$('#myModal').modal('toggle');
           //$('#<?php echo $this->nomForm; ?>')[0].reset();
          // $("#<?php echo $this->nomForm; ?>DirC")[0].reset();
          $("#msj-conf-datos-dir").show();
            
        },'json'

        );

      return false;

    });
      $("#gProveedorDir").click(function(){
      var clientes=$("#<?php echo $this->nomForm; ?>DirP").serialize();
        //alert(clientes);
        //return false;
      $.post("../Proveedores/guardardireccion",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
          // $('#myModal').modal('toggle');
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
           $("#msj-conf-datos-dir-pro").show();
            
        },'json'

        );

      return false;

    });

    $("#aCliente").click(function(){
       // alert("preparar para actulizar");
        var clientes=$("#<?php echo $this->nomForm;?>").serialize();

      $.post("<?php echo $this->actualizaCliente; ?>",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           $("#id_clienteDir").val($("#id_cliente").val());
           
           $("#msj-conf-datos-cliente-actu").show();

          // $('#myModal').modal('toggle');//cerramos el modal despues de agregar dirección
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
            
        },'json'

        );
        return false;


    });
    $("#aClienteDir").click(function(){
       // alert("preparar para actulizar");
        var clientes=$("#<?php echo $this->nomForm;?>DirC").serialize();
       // alert(clientes);
       //return false;
      $.post("<?php echo $this->actualizaDir; ?>",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           //$("#id_clienteDir").val(data.idCliente);
          $("#msj-conf-datos-dir-actu").show();

          // $('#myModal').modal('toggle');//cerramos el modal despues de agregar dirección
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
            
        },'json'

        );
        return false;


    });
     $("#aClientePro").click(function(){
       // alert("preparar para actulizar");
        var clientes=$("#<?php echo $this->nomForm;?>").serialize();
    
      $.post("<?php echo $this->actualizaCliente; ?>",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           $("#id_clienteDir").val($("#id_cliente").val());
           
           $("#msj-conf-datos-cliente-actu").show();

          // $('#myModal').modal('toggle');//cerramos el modal despues de agregar dirección
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
            
        },'json'

        );
        return false;


    });
      $("#aProveedorDir").click(function(){
       // alert("preparar para actulizar");
        var clientes=$("#<?php echo $this->nomForm;?>DirP").serialize();
    
      $.post("<?php echo $this->actualizaDir; ?>",clientes,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
          // $("#id_clienteDir").val($("#id_cliente").val());
           //alert("ddddwdw");
           $("#msj-conf-datos-prov-actu").show();

          // $('#myModal').modal('toggle');//cerramos el modal despues de agregar dirección
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
            
        },'json'

        );
        return false;


    });

     



    /*  $("#btn-direccion").click(function(){
          $("#btn-datos-cliente").trigger("click");
      });*/

         //permisos de usuarios , dato de la base de datos

                   sessionStorage.setItem("actualizar","true");
                   sessionStorage.setItem("eliminar","true");
                   sessionStorage.setItem("suspender","true");
                   sessionStorage.setItem("nuevo","true");
                   sessionStorage.setItem("buscar","true");
                   sessionStorage.setItem("botonesExportar","true");


                  if(sessionStorage.getItem("actualizar")=="false"){
                        $("#editarCliente").attr("disabled",true);
                    }
                    if(sessionStorage.getItem("nuevo")=="false"){
                        $("#btnNuevaOrden").attr("disabled",true);
                    }
                    if(sessionStorage.getItem("suspender")=="false"){
                        $("#suspender").attr("disabled",true);
                    }
                    if(sessionStorage.getItem("buscar")=="false"){
                        $("li").addClass('disabled');
                    }
                    if(sessionStorage.getItem("botonesExportar")=="false"){
                        $(".dt-buttons a").addClass('disabled');
                    }



});




</script>


<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" id="btnNuevaOrden"> <span class="glyphicon glyphicon-plus-sign"></span>Nueva Cotización</button>
  <button class="btn btrn-primary" id='editarCotizacion'><span class="glyphicon glyphicon-pencil"></span>Editar</button>
   <button class="btn btrn-danger" id='suspender'><span class="glyphicon glyphicon-hourglass"></span>Suspender</button>
 

<ul class="pagination ">

   <li id='al' ><a href="#" id='a'>A</a></li>
   <li id="bl"><a href="#" id='b'>B</a></li>
   <li id="cl"><a href="#" id='c'>C</a></li>
   <li id="dl"><a href="#" id='d'>D</a></li>
   <li id="el"><a href="#" id='e'>E</a></li>
   <li id="fl"><a href="#" id='f'>F</a></li>
   <li id="gl"><a href="#" id='g'>G</a></li>
   <li id="hl"><a href="#" id='h'>H</a></li>
   <li id="il"><a href="#" id='i'>I</a></li>
   <li id="jl"><a href="#" id='j'>J</a></li>
   <li id="kl"><a href="#" id='k'>K</a></li>
   <li id="ll"><a href="#" id='l'>L</a></li>
   <li id="ml"><a href="#" id='m'>M</a></li>
   <li id="nl"><a href="#" id='n'>N</a></li>
   <li id="ol"><a href="#" id='o'>O</a></li>
   <li id="pl"><a href="#" id='p'>P</a></li>
   <li id="ql"><a href="#" id='q'>Q</a></li>
   <li id="rl"><a href="#" id='r'>R</a></li>
   <li id="sl"><a href="#" id='s'>S</a></li>
   <li id="tl"><a href="#" id='t'>T</a></li>
   <li id="ul"><a href="#" id='u'>U</a></li>
   <li id="vl"><a href="#" id='v'>V</a></li>
   <li id="wl"><a href="#" id='w'>W</a></li>
   <li id="xl"><a href="#" id='x'>X</a></li>
   <li id="yl"><a href="#" id='y'>Y</a></li>
   <li id="zl"><a href="#" id='z'>Z</a></li>
   <li id="nulll"><a href="#" id='null'>Todos</a></li>
</ul>


  <table id="<?php echo $this->grid; ?>" class="table table-striped table-bordered" cellspacing="0" width="100%" style='font-size:11px;'>
              <thead>
                <tr>
                  <th>Id</th>
                  <th>rComercial</th>
                  <th>Rfc</th>
                  <th>Teléfono</th>
                  <th>Pag.Web</th>
                  <th>Estatus</th>
                 </tr>
              </thead>
              <tbody id="bdy-grid">
            </tbody>
    </table>

<!-- modal para la cotización-->

<div class="modal fade" id="myModal" role="dialog" style='font-size:11px'>
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content" style="border: #deb887 3px solid;">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title" style="color:#deb887;"><?php echo $this->tituloModal; ?></h3>
        </div>
        <div class="modal-body">
             <form  name="<?php echo $this->nomForm;?>" id="<?php echo $this->nomForm;?>" class="form-inline" method="POST">
            
             <table class="table table-condensed">
                <tbody>
                  <tr>
                    <td class="td_right">Cantidad Solicitada:</td>
                    <td colspan="2">
                        <input id="cantidadSol" class="form-control" name="cantidadSol" type="text" value="" required>
                    </td>
                    <td>
                      <button type="button" class="btn btn-default">Limpiar</button>
                    </td>
                  </tr>
                   <tr>
                    <td class="td_right">Articulo:</td>
                    <td colspan="2">
                        <select id='articulo' class="form-control" name="articulo" type="text" value="" required>
                          <option value="">Seleccionar..</option>
                          <option value="1">Caja sin Impresión</option>
                          <option value="2">Caja con Impresión</option>
                        </select>
                    </td>
                   
                  </tr>
                   <tr>
                    <td class="td_right">Tipo de Producto:</td>
                    <td colspan="2">
                        <select id='tipoProducto' class="form-control" name="tipoProducto" type="text" value="" required>
                          <option value="">Seleccionar..</option>
                          <option value="1">Caja sin Impresión</option>
                          <option value="2">Caja con Impresión</option>
                        </select>
                    </td>
                    <td colspan="2">
                    </td>
                    <td colspan="2">
                    </td>

                    <td class="td_right" colspan="2">Precio Unitario</td>
                     <td colspan="2">
                      <input id="precioU" class="form-control" name="precioU" type="hidden" value="" required>
                      <button type="button" class="btn btn-primary">$5000</button>
                    </td>
                    </tr>
                    <tr>
                    <td class="td_right">Tipo de Material:</td>
                    <td colspan="2">
                        <select id='tipoMaterial' class="form-control" name="tipoMaterial" type="text" value="" required>
                          <option value="">Seleccionar..</option>
                          <option value="1">Caja sin Impresión</option>
                          <option value="2">Caja con Impresión</option>
                        </select>
                    </td>
                   
                  </tr>
                   <tr>
                    <td class="td_right">Cartón:</td>
                    <td colspan="2">
                        <select id='carton' class="form-control" name="carton" type="text" value="" required>
                          <option value="">Seleccionar..</option>
                          <option value="1">Caja sin Impresión</option>
                          <option value="2">Caja con Impresión</option>
                        </select>
                    </td>
                   
                  </tr>
                   <tr>
                    <td class="td_right">Importe:</td>
                    <td colspan="2">
                        <input id="importe" class="form-control" name="importe" type="text" value="" required>
                    </td>
                    <td class="td_right">Margen:</td>
                    <td colspan="2">
                        <input id="margen" class="form-control" name="margen" type="text" value="" required>
                    </td>
                     <td colspan="2">
                        <input id="margen" class="form-control" name="margen" type="text" value="" required>
                    </td>
                     <td class="td_right">Importe Total:</td>
                    <td colspan="2">
                     <button type="button" class="btn btn-success">$11000</button>
                        <input id="importeTotal" class="form-control" name="importeTotal" type="hidden" value="" required>
                    </td>
                  </tr>
                   <tr>
                    <td class="td_right">Aplicar Refilado y Rayado:</td>
                    <td colspan="1">
                        <input id="refilado" class="form-control" name="refilado" type="checkbox">
                    </td>
                  </tr>
                   <tr>
                    <td class="td_right">Medidas de Caja:</td>
                    <td colspan="2">
                        <input id="frente" class="form-control" name="frente" type="text" value="" required placeholder="Frente (cm)">
                    </td>
                      <td style="text-align: center;font-weight: bold;">X</td>
                    <td colspan="2">
                       <input id="fondo" class="form-control" name="fondo" type="text" value="" required placeholder="Fondo (cm)">
                    </td>

                    <td colspan="2">
                        <input id="altura" class="form-control" name="altura" type="text" value="" required placeholder="Altura (cm)">
                    </td>

                     <td class="td_right" colspan="2">m^2 Requeridos:</td>
                    <td colspan="2">
                        <input id="requeridos" class="form-control" name="requeridos" type="hidden" value="" required placeholder="m^2 Requeridos">
                        <button type="button" class="btn btn-warning">100</button>
                    </td>
                  </tr>

                  <tr>
                    <td class="td_right">Cartón Requerido:</td>
                    <td colspan="2">
                        <input id="largo" class="form-control" name="largo" type="text" value="" required placeholder="Largo (cm)">
                    </td>
                     <td style="text-align: center;font-weight: bold;">X</td>
                    <td colspan="2">
                       <input id="ancho" class="form-control" name="ancho" type="text" value="" required placeholder="Ancho (cm)">
                    </td>
                    <td >=</td>
                    <td colspan="2">
                        <input id="altura" class="form-control" name="altura" type="text">
                    </td>

                   
                  </tr>

    </tbody>
  </table>
                  

                </div>
            </div>

        </div>
      </div>
    </div>
  </div>


  