<style type="text/css">
tfoot input {
        width: 100%;
        padding: 1px;
        box-sizing: border-box;

    }

    thead{

      background-color: #000000;
      color:#fff;
      height: 2px !important;
    }
    #reporteador_length{
      margin-left: 300px;
    }
    #menu{

      width: 300px;
      height: 100px;
      background-color: black;
    }
    div#<?php echo $this->grid;  ?>_filter.dataTables_filter{
   // display: none !important;
   background-color: #fff !important;
   color: #fff !important;
   z-index: -1!important;
   margin-top: -300px;
}
</style>
<script type="text/javascript">
      var Id;
    $(document).ready(function() {
      MostrarGrid(false);
      $("#msj-guarda-articulo").hide();
      $("#actuArticulo").hide();
      $("#msj-articulo-actu").hide();
    
     $("#"+sessionStorage.getItem("valor")+"l").addClass("active");
    function MostrarGrid(valor){
            $('#<?php echo $this->grid;  ?>').DataTable({
                    "ajax": {
                    "url": "<?php echo $this->urlGrid;?>?valor="+ sessionStorage.getItem("valor")
                },

                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "search": "",
                    "zeroRecords": "No existe el registro",
                    "info": "Página _PAGE_ de _PAGES_",
                    "infoEmpty": "No records available",
                    "infoFiltered": "(Encontrado de _MAX_ registros)",
                    "paginate": {
                        "first":      "Inicio",
                        "last":       "Último",
                        "next":       "Siguiente",
                        "previous":   "Anterior"
                    }
                },
                "lengthMenu": [[10, 20, -1], [10, 20, "Todo"]],

             dom: 'Blfrtip',
      buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ],
     "lengthMenu": [[10, 25, 50,100,200,500,1000 -1], [10, 25, 50,100,200,500,1000, "All"]]
       
            });

            var table = $('#<?php echo $this->grid;  ?>').DataTable();

            $('#<?php echo $this->grid;  ?> tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');

             Id = $(this).find('td').eq(0).html();
            $("#id").val(Id);
            OrdenID=$("#id").val();

       
            }

        });

        //editar
         $("#cancelar").click(function(){
            $('#<?php echo $this->nomForm;?>')[0].reset();
            window.location="<?php echo $this->baseUrl; ?>";
        });
    $("#editarArticulo").click(function(){
          // alert(Id);
            
            $("#guardarArticulo").hide();
            $("#actuArticulo").show();
            //return false;
            if(Id != ""){

     $.post("<?php echo $this->consultaarticulo; ?>",{id_articulo:Id},
                function(data){
                  $("#id_articulo").val(data.datos[0].id_articulo);
                  $("#clave").val(data.datos[0].clave);
                  $("#descripcion").val(data.datos[0].descripcion);
                  $("#id_categoria").val(data.datos[0].id_categoria);
                  $("#costo").val(data.datos[0].costo);
                  $("#margen").val(data.datos[0].margen);
                  $("#precio").val(data.datos[0].precio);
                  $("#precio_anterior").val(data.datos[0].precio_anterior);
                  $("#unidad").val(data.datos[0].unidad);
                  $("#id_estatus").val(data.datos[0].id_estatus);
                

                  $("#btnNuevaOrden").trigger("click");
                },'json'

                );

              
            }
           

        });

      //boton de suspender
      $("#suspender").click(function(){

        alert("suspender a " + Id);

      });
        
    }


     $("#buscadorGeneral").change(function(){
        //alert("hola");
                 $("[aria-controls='<?php echo $this->grid; ?>']").val($("#buscadorGeneral").val());
                 $('#<?php echo $this->grid; ?>_filter input').attr("placeholder", "BUSCAR");
                 $('#<?php echo $this->grid; ?>_filter input').addClass("text-uppercase");
                 $('#<?php echo $this->grid; ?>_filter input').focus();
                });

     $(".pagination li a").click(function(){
             sessionStorage.setItem("valor", $(this).attr("id"));
             window.location='<?php echo $this->redireccionar; ?>';
            $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();

     });


     //funcionalidades para guardar
     $("#<?php echo $this->nomForm;?>").submit(function(){
      var clientes=$("#<?php echo $this->nomForm;?>").serialize();
       
      $.post("<?php echo $this->guardarArticulo; ?>",clientes,
        function(data){

          $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
          $("#msj-guarda-articulo").show();  
          
        },'json'

        );
   return false;

    });
    
    $("#actuArticulo").click(function(){
       // alert("preparar para actulizar");
        var articulos=$("#<?php echo $this->nomForm;?>").serialize();
      $.post("<?php echo $this->actualizaCliente; ?>",articulos,
        function(data){

           $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           $("#id_clienteDir").val($("#id_cliente").val());
           
           $("#msj-articulo-actu").show();
   
        },'json'

        );
        return false;


    });
   
         //permisos de usuarios , dato de la base de datos

                   sessionStorage.setItem("actualizar","true");
                   sessionStorage.setItem("eliminar","true");
                   sessionStorage.setItem("suspender","true");
                   sessionStorage.setItem("nuevo","true");
                   sessionStorage.setItem("buscar","true");
                   sessionStorage.setItem("botonesExportar","true");


                  if(sessionStorage.getItem("actualizar")=="false"){
                        $("#editarCliente").attr("disabled",true);
                    }
                    if(sessionStorage.getItem("nuevo")=="false"){
                        $("#btnNuevaOrden").attr("disabled",true);
                    }
                    if(sessionStorage.getItem("suspender")=="false"){
                        $("#suspender").attr("disabled",true);
                    }
                    if(sessionStorage.getItem("buscar")=="false"){
                        $("li").addClass('disabled');
                    }
                    if(sessionStorage.getItem("botonesExportar")=="false"){
                        $(".dt-buttons a").addClass('disabled');
                    }



});




</script>


<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" id="btnNuevaOrden"> <span class="glyphicon glyphicon-plus-sign"></span>Nuevo</button>
  <button class="btn btrn-primary" id='editarArticulo'><span class="glyphicon glyphicon-pencil"></span>Editar</button>
   <button class="btn btrn-danger" id='suspender'><span class="glyphicon glyphicon-hourglass"></span>Suspender</button>
 

<ul class="pagination ">

   <li id='al' ><a href="#" id='a'>A</a></li>
   <li id="bl"><a href="#" id='b'>B</a></li>
   <li id="cl"><a href="#" id='c'>C</a></li>
   <li id="dl"><a href="#" id='d'>D</a></li>
   <li id="el"><a href="#" id='e'>E</a></li>
   <li id="fl"><a href="#" id='f'>F</a></li>
   <li id="gl"><a href="#" id='g'>G</a></li>
   <li id="hl"><a href="#" id='h'>H</a></li>
   <li id="il"><a href="#" id='i'>I</a></li>
   <li id="jl"><a href="#" id='j'>J</a></li>
   <li id="kl"><a href="#" id='k'>K</a></li>
   <li id="ll"><a href="#" id='l'>L</a></li>
   <li id="ml"><a href="#" id='m'>M</a></li>
   <li id="nl"><a href="#" id='n'>N</a></li>
   <li id="ol"><a href="#" id='o'>O</a></li>
   <li id="pl"><a href="#" id='p'>P</a></li>
   <li id="ql"><a href="#" id='q'>Q</a></li>
   <li id="rl"><a href="#" id='r'>R</a></li>
   <li id="sl"><a href="#" id='s'>S</a></li>
   <li id="tl"><a href="#" id='t'>T</a></li>
   <li id="ul"><a href="#" id='u'>U</a></li>
   <li id="vl"><a href="#" id='v'>V</a></li>
   <li id="wl"><a href="#" id='w'>W</a></li>
   <li id="xl"><a href="#" id='x'>X</a></li>
   <li id="yl"><a href="#" id='y'>Y</a></li>
   <li id="zl"><a href="#" id='z'>Z</a></li>
   <li id="nulll"><a href="#" id='null'>Todos</a></li>
</ul>


  <table id="<?php echo $this->grid; ?>" class="table table-striped table-bordered" cellspacing="0" width="100%" style='font-size:11px;'>
              <thead>

                <tr>
                  <th>Id</th>
                  <th>Usuario</th>
                  <th>Password</th>
                  <th>Correo</th>
                  <th>id_estatus</th>
                  <th>id_tipo_usuario</th>
                 </tr>
              </thead>
              <tbody id="bdy-grid">
            </tbody>
    </table>

    <div class="modal fade" id="myModal" role="dialog" style='font-size:11px;'>
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" style="color:#deb887;"><?php echo $this->tituloModal; ?></h4>
        </div>
        <div class="modal-body">
            <?php  if($this->identificador=="articulo"){ ?>
             <form  name="<?php echo $this->nomForm;?>" id="<?php echo $this->nomForm;?>" class="form-inline" method="POST">
               <input id="id_articulo" class="form-control" name="id_articulo" type="hidden" value="" required>
             <table class="table table-striped">
                <tbody>

                    <tr>
                    <td class="td_right">Clave:</td>
                    <td colspan="3">
                        <input id="clave" class="form-control" name="clave" type="text" value="" required>
                    </td>
                    <td class="td_right">Descripción:</td>
                    <td colspan="6">
                       <textarea id="descripcion" name="descripcion" rows="4" cols="100"></textarea>
                    </td>
                   </tr>
                 <tr>
                  <td class="td_right">Categoría:</td>
                    <td colspan="3">
                        <select id='id_categoria' class="form-control" name="id_categoria" type="text" value="" required>
                          <option value="">Seleccionar..</option>
                          <option value="1">cat1</option>
                          <option value="2">cat2</option>
                          <option value="3">cat3</option>
                        </select>
                    </td>
                    <td class="td_right">Costo:</td>
                    <td colspan="3">
                        <input id="costo" class="form-control" name="costo" type="text" value="" required>
                    </td>
                    <td class="td_right">Margen:</td>
                    <td colspan="3">
                        <input id="margen" class="form-control" name="margen" type="text" value="" required>
                    </td>
                </tr>
                <tr>
                    <td class="td_right">Precio:</td>
                    <td colspan="3">
                        <input id="precio" class="form-control" name="precio" type="text" value="" required>
                    </td>
                    <td class="td_right">Precio anterior:</td>
                    <td colspan="3">
                        <input id="precio_anterior" class="form-control" name="precio_anterior" type="text" value="" required>
                    </td>
                    <td class="td_right">Unidad:</td>
                    <td colspan="3">
                        <input id="unidad" class="form-control" name="unidad" type="text" value="" required>
                    </td>
                </tr>
                <tr>
                 <td class="td_right">Estatus:</td>
                    <td colspan="3">
                        <select id='id_estatus' class="form-control" name="id_estatus" type="text" value="" required>
                          <option value="">Seleccionar..</option>
                          <option value="1">Activo</option>
                          <option value="2">Inactivo</option>
                          <option value="3">Suspendido</option>
                        </select>
                    </td>
                </tr>
               </tbody>
            </table>

              <button type="submit" class="btn btn-success"  id="guardarArticulo" style="float: right;margin-top: -30px;"><span class="glyphicon glyphicon-ok" ></span>Guardar</button>
            </form>
             <button type="submit" class="btn btn-success"  id="actuArticulo" style="float: right;margin-top: -30px;"><span class="glyphicon glyphicon-refresh" ></span>Actualizar</button>
            </form>

            <div class="alert alert-success" id='msj-guarda-articulo' style="font-size:24px !important;">
            <strong>Aviso!</strong> Artículo Guardado con éxito.
            </div>
            <div class="alert alert-success" id='msj-articulo-actu' style="font-size:24px !important;">
            <strong>Aviso!</strong> Artículo actualizado con éxito.
            </div>


            <?php } ?>
    
        <div class="modal-footer">
         <button type="submit" class="btn btn-default" data-dismiss="modal" id="cancelar"><span class="glyphicon glyphicon-remove"></span>Cerrar</button>
        

        </div>
        </div>
      </div>
      
    </div>
  </div>