<!--style type="text/css">
tfoot input {
  width: 100%;
  padding: 1px;
  box-sizing: border-box;

}

thead{

  background-color: #000000;
  color:#fff;
  height: 2px !important;
}
#reporteador_length{
  margin-left: 300px;
}
#menu{

  width: 300px;
  height: 100px;
  background-color: black;
}
div#<?php //echo $this->grid;  ?>_filter.dataTables_filter{
 // display: none !important;
 background-color: #fff !important;
 color: #fff !important;
 z-index: -1!important;
 margin-top: -300px;
}
</style-->
<style>
.modal-dialog {
  width: 80%;
}  
</style>
<script type="text/javascript">
  var Id;
  $(document).ready(function() {
    MostrarGrid(false);
    $("#msj-conf-datos-cliente").hide();
    $("#msj-conf-datos-cliente-actu").hide();
    $("#msj-conf-datos-dir-actu").hide();
    $("#msj-conf-datos-dir").hide();
    $("#msj-conf-datos-dir-pro").hide();
    $("#msj-conf-datos-prov-actu").hide();

    $( ".buttons-excel" ).hide();

     //ocultar boton de actualizar
     $("#aCliente").hide();
     $("#aClienteDir").hide();
     $("#aClientePro").hide();
     $("#aProveedorDir").hide();
     $("#"+sessionStorage.getItem("valor")+"l").addClass("active");
     function MostrarGrid(valor){
      $('#<?php echo $this->grid;  ?>').DataTable({
        "ajax": {
          "url": "<?php echo $this->urlGrid;?>&valor="+ sessionStorage.getItem("valor")
        },
        "lengthChange": false,
        "language": {
          //"lengthMenu": "Mostrar _MENU_ registros por página",
          "search": "",
          "zeroRecords": "No existen direcciónes para <?php echo $this->nombreCliente;  ?>",
          "info": "Página _PAGE_ de _PAGES_",
          "infoEmpty": "No existen direcciónes para <?php echo $this->nombreCliente;  ?>",
          "infoFiltered": "(Encontrado de _MAX_ registros)",
          "paginate": {
            "first":      "Inicio",
            "last":       "Último",
            "next":       "Siguiente",
            "previous":   "Anterior"
          }
        },
        //"lengthMenu": [[10, 20, -1], [10, 20, "Todo"]],

        dom: 'frtiB',
        buttons: ['excel'],
      /*  "columnDefs": [
    { "width": "50%", "targets": 0 }
    ],*/
    //"lengthMenu": [[10, 25, 50,100,200,500,1000 -1], [10, 25, 50,100,200,500,1000, "All"]]
    
  });

      var table = $('#<?php echo $this->grid;  ?>').DataTable();
      
      $( "#btn-excel" ).on( "click", function() {
        $( ".buttons-excel" ).trigger( "click" );
      });

      $('#<?php echo $this->grid;  ?> tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
          $(this).removeClass('selected');
        }
        else {
          table.$('tr.selected').removeClass('selected');
          $(this).addClass('selected');

          Id = $(this).find('td').eq(0).html();
          $("#id").val(Id);
          OrdenID=$("#id").val();

          
        }

      });

        //editar
        $("#cancelar").click(function(){


          $('#<?php echo $this->nomForm;?>DirC')[0].reset();
          window.location="<?php echo $this->baseUrl; ?>";
        });
        $("#editarDireccion").click(function(){
          // alert(Id);
          
          $("#gClienteDir").hide();
          $("#aClienteDir").show();

          var title = "Editar dirección";
          $("#myModal .modal-title").text( title );
            //return false;
            if(Id != ""){

             $.post("<?php echo $this->consultaDireccion; ?>",{direccion:Id},
              function(data){
                $("#id_tipodireccion").val(data.datos[0].id_tipodireccion);
                $("#id_direccion").val(data.datos[0].id_direccion);
                $("#estatusDir").val(data.datos[0].id_estatus);
                $("#calle").val(data.datos[0].calle);
                $("#colonia").val(data.datos[0].colonia);
                $("#ciudad").val(data.datos[0].ciudad);
                $("#municipio").val(data.datos[0].municipio);
                $("#estado").val(data.datos[0].estado);
                $("#cp").val(data.datos[0].cp);
                $("#nota").val(data.datos[0].nota);

                $("#btnNuevaOrden").trigger("click");
              },'json'

              );

             
           }
           

         });

      //boton de suspender
      $("#suspender").click(function(){

        alert("suspender a " + Id);

      });
      $("#regresar").click(function(){
        sessionStorage.setItem("valor","null");
        window.location='<?php echo $this->regresar; ?>';

      });


      
    }


    $("#buscadorGeneral").change(function(){
        //alert("hola");
        $("[aria-controls='<?php echo $this->grid; ?>']").val($("#buscadorGeneral").val());
        $('#<?php echo $this->grid; ?>_filter input').attr("placeholder", "BUSCAR");
        $('#<?php echo $this->grid; ?>_filter input').addClass("text-uppercase");
        $('#<?php echo $this->grid; ?>_filter input').focus();
      });

    /*$(".pagination li a").click(function(){
     sessionStorage.setItem("valor", $(this).attr("id"));
     window.location='<?php echo $this->redireccionar; ?>';
     $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();

   });*/


     //funcionalidades para guardar
     $("#gClienteDir").click(function(){
      var clientes=$("#<?php echo $this->nomForm; ?>DirC").serialize();
      
      $.post("../Clientes/guardardireccion",clientes,
        function(data){

         $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           //$('#myModal').modal('toggle');
           $('#<?php echo $this->nomForm; ?>DirC')[0].reset();
          // $("#<?php echo $this->nomForm; ?>DirC")[0].reset();
          $("#msj-conf-datos-dir").show();
          
        },'json'

        );

      return false;

    });
     
     $("#aClienteDir").click(function(){
       // alert("preparar para actulizar");
       var clientes=$("#<?php echo $this->nomForm;?>DirC").serialize();
       // alert(clientes);
       //return false;
       $.post("<?php echo $this->actualizaDir; ?>",clientes,
        function(data){

         $('#<?php echo $this->grid;  ?>').dataTable()._fnAjaxUpdate();
           //$("#id_clienteDir").val(data.idCliente);
           $("#msj-conf-datos-dir-actu").show();

          // $('#myModal').modal('toggle');//cerramos el modal despues de agregar dirección
          // $('#<?php echo $this->nomForm; ?>')[0].reset();
          
        },'json'

        );
       return false;


     });
     
         //permisos de usuarios , dato de la base de datos

         sessionStorage.setItem("actualizar","true");
         sessionStorage.setItem("eliminar","true");
         sessionStorage.setItem("suspender","true");
         sessionStorage.setItem("nuevo","true");
         sessionStorage.setItem("buscar","true");
         sessionStorage.setItem("botonesExportar","true");


         if(sessionStorage.getItem("actualizar")=="false"){
          $("#editarCliente").attr("disabled",true);
        }
        if(sessionStorage.getItem("nuevo")=="false"){
          $("#btnNuevaOrden").attr("disabled",true);
        }
        if(sessionStorage.getItem("suspender")=="false"){
          $("#suspender").attr("disabled",true);
        }
        if(sessionStorage.getItem("buscar")=="false"){
          $("li").addClass('disabled');
        }
        if(sessionStorage.getItem("botonesExportar")=="false"){
          $(".dt-buttons a").addClass('disabled');
        }



      });




    </script>

<div class="row">
  <div class="col-md-8">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="btnNuevaOrden"> <span class="glyphicon glyphicon-plus-sign"></span>Nuevo</button>
    <button class="btn btn-primary" id='editarDireccion'><span class="glyphicon glyphicon-pencil"></span>Editar</button>
    <button class="btn btn-primary" id='suspender'><span class="glyphicon glyphicon-hourglass"></span>Suspender</button>
    <button class="btn btn-primary" id='regresar'><span class="glyphicon glyphicon-arrow-left"></span>Regresar</button>
    <button class="btn btn-primary" id='btn-excel'>Exportar a Excel</button>    
  </div>
  <div class="col-md-4"><h1>**Direcciones**</h1></div>
</div>
<br>
    
    <table id="<?php echo $this->grid; ?>" class="table compact cell-border" cellspacing="0" width="100%" style='font-size:11px;'>
      <thead>
       <tr>
        <th>Id</th>
        <th>Calle</th>
        <th>Colonia</th>
        <th>Ciudad</th>
        <th>Municipio</th>
        <th>Estado</th>
        <th>Cp</th>
        <th>Nota</th>
        <th>Estatus</th>
        
      </tr>
    </thead>
    <tbody id="bdy-grid">
    </tbody>
  </table>

  <div class="modal fade" id="myModal" role="dialog" style='font-size:11px;'>
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" style="color:#deb887;"><?php echo $this->tituloModal; ?></h4>
        </div>
        <div class="modal-body">
          <?php  if($this->identificador=="direccion"){ ?>
          <form  name="<?php echo $this->nomForm;?>" id="<?php echo $this->nomForm;?>DirC" class="form-inline" method="POST">
           <input type="hidden" id="id_clienteDir" name="id_cliente" value='<?php echo $this->cliente; ?>'></input>
           <input type="hidden" id="id_direccion" name="id_direccion" ></input>
           <table class="table compact cell-border">
            <tbody>
              <tr>
                <td class="td_right">Tipo Dirección:</td>
                <td colspan="3">
                  <select id='id_tipodireccion' class="form-control" name="id_tipodireccion" type="text" value="" required>
                    <option value="">Seleccionar..</option>
                    <option value="1">dir1</option>
                    <option value="2">dir2</option>
                    <option value="3">dir3</option>
                  </select>
                </td>
                <td class="td_right">Estatus:</td>
                <td colspan="3">
                 <select id='estatusDir' class="form-control" name="id_estatus" type="text" value="" required>
                  <option value="">Seleccionar..</option>
                  <option value="1">Activo</option>
                  <option value="2">Inactivo</option>
                  <option value="3">Suspendido</option>
                </select>
              </td>
              <td class="td_right">Calle:</td>
              <td colspan="3">
                <input id="calle" class="form-control" name="calle" type="text" value="" required>
              </td>
            </tr>
            <tr>
              <td class="td_right">Colonia:</td>
              <td colspan="3">
                <input id="colonia" class="form-control" name="colonia" type="text" value="" required>
              </td>
              <td class="td_right">Ciudad:</td>
              <td colspan="3">
                <input id="ciudad" class="form-control" name="ciudad" type="text" value="" required>
              </td>
              <td class="td_right">Municipio:</td>
              <td colspan="3">
                <input id="municipio" class="form-control" name="municipio" type="text" value="" required>
              </td>
            </tr>
            <tr>
              <td class="td_right">Estado:</td>
              <td colspan="3">
                <input id="estado" class="form-control" name="estado" type="text" value="" required>
              </td>
              <td class="td_right">Cp:</td>
              <td colspan="3">
                <input id="cp" class="form-control" name="cp" type="text" value="" required>
              </td>
              <td class="td_right">Nota:</td>
              <td colspan="3">
               <textarea id="nota" class="form-control" name="nota" required rows="4" cols="50"></textarea>
             </td>
           </tr>
           <tr>
            <td colspan="12">
              <button type="submit" class="btn btn-success" data-dismiss="modal" id='aClienteDir' style="float: right;"> <span class="glyphicon glyphicon-refresh"></span>Actualizar</button>
              <button type="submit" class="btn btn-success" data-dismiss="modal" id='gClienteDir' style="float: right;"> <span class="glyphicon glyphicon-ok"></span>Guardar</button>
            </td>
          </tr>
        </tbody>
      </table>
    </form>
    <div class="alert alert-success" id='msj-conf-datos-dir-actu' style="font-size:24px !important;">
      <strong>Aviso!</strong> Dirección actualizada con éxito.
    </div>
    <div class="alert alert-success" id='msj-conf-datos-dir' style="font-size:24px !important;">
      <strong>Aviso!</strong> Dirección Guardada con éxito.

    </div>

    <?php } ?>
    
    <div class="modal-footer">
     <button type="submit" class="btn btn-default" data-dismiss="modal" id="cancelar"><span class="glyphicon glyphicon-remove"></span>Cerrar</button>
     

   </div>
 </div>
</div>

</div>
</div>