<div class="row">
  <div class="col-md-9">
    <button id="btn-nueva" class="btn btn-primary">Nueva</button>
    <button id="btn-recuperar" class="btn btn-primary">Recuperar</button>
    <a class="btn btn-primary" href="#!" role="button" id="btn-imprimir" target="FormatoPDF">Imprimir</a>
  </div>  
  <div class="col-md-3"><h1><?php  echo $this->titulo; echo @$this->nombreCliente?></h1></div>
</div>
<div class="row">
	<div class="col-md-12">
		<table id="listacarton" class="compact cell-border" cellspacing="0" width="100%" style="text-align: center;">
			<thead>
				<tr>
					<th>Id_cotizacion</th>
					<th>Nombre Trabajo</th>
					<th>Nombre Cliente</th>
					<th>Fecha Emisión</th>
				</tr>
			</thead>
			<tbody>
				<!--Registro de la BD-->
			</tbody>
		</table>				
	</div> 	
</div>

<script>

	$("#btn-nueva").attr('disabled', false);
	$("#btn-recuperar").attr('disabled', true);
	//$("#btn-imprimir").attr('disabled', true);

	var listacarton = $('#listacarton').DataTable({
		ajax:{
			url: 'consultarcotizaciones'
		}, 	
		"columns":[
		{data:"id_cotizacion",width:"5%"},
		{data:"nombre_trabajo",width:"40%"},
		{data:"nombre_cliente",width:"40%"},
		{data:"fecha_emision",width:"10%"},
		],
		"columnDefs": 
		[
		{"className": "dt-body-left", "targets": [1]},
		{"className": "dt-head-center", "targets": "_all"}
		],	
		"order": [[0, "desc" ]],
		"searching": true,
		"paging":    false,
		"scrollY":   '320px',
		"scrollX": true			
	});

	$('#listacarton tbody').on( 'click', 'tr', function () {
		if ( $(this).hasClass('selected') ) {
			$(this).removeClass('selected');
			$("#btn-nueva").attr('disabled', false);
			$("#btn-recuperar").attr('disabled', true);
			$("#btn-imprimir").attr('disabled', true);
		}
		else {
			listacarton.$('tr.selected').removeClass('selected');
			$(this).addClass('selected');
			$("#btn-nueva").attr('disabled', true);
			$("#btn-recuperar").attr('disabled', false);
			//$("#btn-imprimir").attr('disabled', false);

		}

		var id = $(this).find('td').eq(0).html();

		$("#btn-recuperar").click(function(){
			window.location.href = "show?ID="+id+"&Tipo=2&id="+id;
		});

		//$("a[id='btn-imprimir']").attr('href', 'orderpdf?Id='+id);

		return false;

	});

	$("#btn-nueva").click(function(){

		window.location.href = "carton";

	});



</script>