<?php 
$this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css');
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js','text/javascript');
?>

<style>
.modal-dialog {
  width: 70%;
}  

.modal-clientes{
  font-size: 12px;
  //width: 80%;
  //height: 25px;
}
</style>
<div class="row">  
<div class="col-md-8">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#detalleModal" id="btnnuevocliente">Nuevo</button>
  <!--button class="btn btn-primary" id='editarCliente'><span class="glyphicon glyphicon-pencil"></span>Editar</button>
   <button class="btn btn-primary" id='suspender'><span class="glyphicon glyphicon-hourglass"></span>Suspender</button-->
   <button class="btn btn-primary" id='excel-clientes'>Exportar a Excel</button>
 </div>
<div class="col-md-4"><h1><?php  echo $this->titulo; echo @$this->nombreCliente?></h1></div>
</div> 

<div class="row">
<div class="col-md-12">
<table id="catClientes" class="compact cell-border" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Id</th>
      <th>Razón Comercial</th>
      <th>RFC</th>
      <th>Teléfono</th>
      <th>Pag.Web</th>
      <th>Estatus</th>
      <th>Detalle</th>
      <th>Dirección</th>
    </tr>
  </thead>

  <tbody id="bdy-grid">
  </tbody>
</table>
</div>
</div>

    <!-- Modal  Detalle -->
    <div class="modal fade" id="detalleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Detalle Clientes</h4>
          </div>
          <div class="modal-body">
            <form id="frmactualizarcliente" method="POST" action="extraercliente" style="font-size:10px;">
              <div class="row">
                <!--div class="col-md-12"-->
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="rcomercial" class="control-label">Razón Comercial</label>
                      <input type="text" class="form-control modal-clientes" id="rcomercial" name="rcomercial" required>
                    </div>
                  </div>
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="rfc" class="control-label">Rfc</label>
                      <input type="text" class="form-control modal-clientes" id="rfc" name="rfc" required>
                    </div>
                  </div>
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="telefono" class="control-label">Telefono</label>
                      <input type="number" class="form-control modal-clientes" id="telefono" name="telefono" required>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="pagweb" class="control-label">Pag.Web</label>
                      <input type="text" class="form-control modal-clientes" id="pagweb" name="pagweb" required>
                    </div>
                  </div>                                                                                 
                <!--/div-->
                <!--div class="col-md-12"-->
                    <div class="form-group col-md-4">
                      <label for="categoria">Categoria</label>
                      <select class="form-control" id="categoria" name="categoria" required>                       
                      </select>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="estatus">Estatus</label>
                      <select class="form-control" id="estatus" name="estatus">                               
                      </select>
                    </div>              
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="cpago" class="control-label">Condición de pago</label>
                      <input type="number" class="form-control modal-clientes" id="cpago" name="cpago" required>
                    </div>
                  </div>              
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="drevision" class="control-label">Días de revisión</label>
                      <input type="number" class="form-control modal-clientes" id="drevision" name="drevision" required>
                    </div>
                  </div>              
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="contacto1" class="control-label">Contacto 1:</label>
                      <input type="text" class="form-control modal-clientes" id="contacto1" name="contacto1" required>
                    </div>
                  </div>  
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="mobilcontacto1" class="control-label">Email:</label>
                      <input type="text" class="form-control modal-clientes" id="mailcontacto1" name="mailcontacto1" required>
                    </div>
                  </div> 
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="referencia1" class="control-label">Referencia:</label>
                      <input type="text" class="form-control modal-clientes" id="referencia1" name="referencia1" required>
                    </div>
                  </div> 

                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="contacto2" class="control-label">Contacto 2:</label>
                      <input type="text" class="form-control modal-clientes" id="contacto2" name="contacto2" required>
                    </div>
                  </div>  
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="mailcontacto2" class="control-label">Email:</label>
                      <input type="text" class="form-control modal-clientes" id="mailcontacto2" name="mailcontacto2" required>
                    </div>
                  </div> 
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="referencia2" class="control-label">Referencia:</label>
                      <input type="text" class="form-control modal-clientes" id="referencia2" name="referencia2" required>
                    </div>
                  </div>    

                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="contacto3" class="control-label">Contacto 3:</label>
                      <input type="text" class="form-control modal-clientes" id="contacto3" name="contacto3" required>
                    </div>
                  </div>  
                  <div class="col-md-2">
                    <div class="form-group">
                      <label for="mailcontacto3" class="control-label">Email:</label>
                      <input type="text" class="form-control modal-clientes" id="mailcontacto3" name="mailcontacto3" required>
                    </div>
                  </div> 
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="referencia3" class="control-label">Referencia:</label>
                      <input type="text" class="form-control modal-clientes" id="referencia3" name="referencia3" required>
                    </div>
                  </div>                                

                    <div class="form-group col-md-4">
                      <label for="vendedor">Vendedor</label>
                      <select class="form-control" id="vendedor" name="vendedor" required>
                      </select>
                    </div>
                <!--/div-->                                                                      
              </div>         
            </form>        
          </div>
          <div class="modal-footer">
            <button id="cancelar" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button id="nuevocliente" type="button" class="btn btn-primary">Guardar</button>
            <button id="actualizarcliente" type="button" class="btn btn-primary">Actualizar</button>
          </div>
        </div>
      </div>
    </div>

    <script>
var idcliente;  

        $.ajax({
          type: "GET",
          url: 'llenarcombotiposestatus',          
          dataType: "json",          
          //async: false,
          //type: "POST",
          success: function(data){
            $('select[name="estatus"]').append(data);
          }
        });

        $.ajax({
          type: "GET",
          url: 'llenarcombocategorias',          
          dataType: "json",          
          //async: false,
          //type: "POST",
          success: function(data){
            $('select[name="categoria"]').append(data);
          }
        });        

        $.ajax({
          type: "GET",
          url: 'llenarcombovendedores',          
          dataType: "json",          
          //async: false,
          //type: "POST",
          success: function(data){
            $('select[name="vendedor"]').append(data);
          }
        });       

  var catClientes = $('#catClientes').DataTable({
    ajax:{
      url: 'consultarclientes'
    },  
    //"info" : false,
    //"searching": false,
    "paging":    false,
    "scrollY":   '58vh',
    //"scrollX": true 
        dom: 'Blfrtip',
          buttons: [
            'excel'
        ],      
    "columns":[
      {data:"id_cliente"},
      {data:"rcomercial"},
      {data:"rfc"},
      {data:"telefono"},
      {data:"pagweb"},
      {data:"id_estatus"},
      {data:"detalle"},
      {data:"direccion"}
    ],  
    "columnDefs": [
    {
      "className": "dt-center",
      "targets": [5,6,7]
    },
    ]         
  }); 

  $( ".buttons-excel" ).hide(); 
      $( "#excel-clientes" ).on( "click", function() {
        $( ".buttons-excel" ).trigger( "click" );
      });   

  $('#catClientes').on("click", "a.btn-detalles", function () 
  {
    $("#nuevocliente").hide();
    $("#actualizarcliente").show();
    var data = catClientes.row($(this).parents("tr")).data();
    idcliente = data.id_cliente;        

    $.post('extraercliente', {idcliente:idcliente},
      function(result)
      {
      console.log(result);       
          $("#rcomercial").val(result.rcomercial);
          $("#rfc").val(result.rfc);  
          $("#telefono").val(result["telefono"]);
          $("#pagweb").val(result.pagweb);
          //$("#categoria").val(result.categoria);
          $('select[name="categoria"]>option').removeAttr("selected");
          $('select[name="categoria"]>option[value="'+result.id_categoria+'"]').attr("selected", true);  
          $('select[name="estatus"]>option').removeAttr("selected");
          $('select[name="estatus"]>option[value="'+result.id_estatus+'"]').attr("selected", true);  
          $("#cpago").val(result.condpago);
          $("#drevision").val(result.diasrevision);
          $("#contacto1").val(result.contacto1);
          $("#mailcontacto1").val(result.mailcont1);
          $("#referencia1").val(result.refcont1);
          $("#contacto2").val(result.contacto2);
          $("#mailcontacto2").val(result.mailcont2);
          $("#referencia2").val(result.refcont2);
          $("#contacto3").val(result.contacto3);
          $("#mailcontacto3").val(result.mailcont3);
          $("#referencia3").val(result.refcont3);
          $('select[name="vendedor"]>option').removeAttr("selected");
          $('select[name="vendedor"]>option[value="'+result.id_vendedor+'"]').attr("selected", true);           
          $("#detalleModal").modal('show'); 
      },'json'
    );
    
  });

  $("#actualizarcliente").click(function(){
    var cadena = $("#frmactualizarcliente").serialize()+'&id_cliente='+idcliente;
    console.log(cadena);
    $.post('actualizarcliente', cadena,
      function(result)
      {
        swal("Actualizado","success");
        $("#detalleModal").modal('hide');
        catClientes.ajax.reload();
      },'json'
    );
  });

  $("#btnnuevocliente").click(function(){
    $("#actualizarcliente").hide();
    $("#nuevocliente").show();
    $("#rcomercial").val("");
    $("#rfc").val("");  
    $("#telefono").val("");
    $("#pagweb").val("");
    $("#categoria").val("");
    $("select[id=categoria]").val("0");
    $("select[id=estatus]").val("0");   
    $("#estado").val("");
    $("#drevision").val("");
    $("#contacto1").val("");
    $("#mailcontacto1").val("");
    $("#referencia1").val("");
    $("#contacto2").val("");
    $("#mailcontacto2").val("");
    $("#referencia2").val("");
    $("#contacto3").val("");
    $("#mailcontacto3").val("");
    $("#referencia3").val("");
    $("select[id=vendedor]").val("0");  
  });

  $("#nuevocliente").click(function(){
    var cadena = $("#frmactualizarcliente").serialize();
    console.log(cadena);
    $.post('insertarcliente', cadena,
      function(result)
      {
        swal("Se registro","success");
        $("#detalleModal").modal('hide');
        catClientes.ajax.reload();
      },'json'
    );    
  }); 

    $('#catClientes').on("click", "a.btn-direccioncliente", function () 
    {
    var data = catClientes.row($(this).parents("tr")).data();
    idcliente = data.id_cliente;  
    var nombrecliente =data.rcomercial;
      window.location.href = "direccioncliente?ID="+idcliente+"&nombrecliente="+nombrecliente;

    });

</script>