  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="btnNuevaOrden">Nuevo</button>
    <button class="btn btn-primary" id='editarCliente'>Editar</button>
    <button class="btn btn-primary" id='suspender'>Suspender</button>
    <button class="btn btn-primary" id='btn-excel'>Exportar a Excel</button>

<table id="<?php echo $this->grid; ?>" class="table display cell-border" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Id</th>
      <th>rComercial</th>
      <th>Rfc</th>
      <th>Teléfono</th>
      <th>Pag.Web</th>
      <th>Estatus</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="bdy-grid">
  </tbody>
</table>

