<style>
.modal-dialog {
  width: 70%;
}  

.modal-clientes{
  font-size: 12px;
  //width: 80%;
  //height: 25px;
}
</style>
<div class="row">  
  <div class="col-md-8">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#detalleModal" id="btnnuevomaterial">Nuevo</button>
  <!--button class="btn btn-primary" id='editarCliente'><span class="glyphicon glyphicon-pencil"></span>Editar</button>
  <button class="btn btn-primary" id='suspender'><span class="glyphicon glyphicon-hourglass"></span>Suspender</button-->
   <button class="btn btn-primary" id='excel-materiales'>Exportar a Excel</button>
 </div>
 <div class="col-md-4"><h1><?php  echo $this->titulo; echo @$this->nombreCliente?></h1></div>
</div> 

<div class="row">
  <div class="col-md-12">
    <table id="catMateriales" class="compact cell-border" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Id</th>
          <th>Clave</th>
          <th>Descripción</th>
          <th>Id_Proveedor</th>
          <th>Id_Categoria</th>
          <th>Costo</th>
          <th>Unidad</th>
          <th>Estatus</th>
          <th>Detalle</th>
        </tr>
      </thead>

      <tbody id="bdy-grid">
      </tbody>
    </table>
  </div>
</div>

<!-- Modal  Reporte -->
<div class="modal fade" id="detalleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Detalle Materiales</h4>
      </div>
      <div class="modal-body">
        <form id="frmactualizarmaterial" method="POST" action="extraerproveedor" style="font-size:10px;">
          <div class="row">
            <!--div class="col-md-12"-->
            <div class="col-md-4">
              <div class="form-group">
                <label for="clave" class="control-label">Calve</label>
                <input type="text" class="form-control modal-clientes" id="clave" name="clave">
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label for="descripcion" class="control-label">Descripción</label>
                <textarea class="form-control" id="descripcion" name="descripcion" rows="3"></textarea>
              </div>
            </div>
            <div class="form-group col-md-4">
              <label for="id_cli-prov">Proveedor</label>
              <select class="form-control" id="id_cli-prov" name="id_cli-prov" required>
                <option value="" selected disabled>ELIGE UNA OPCIÓN</option>
              </select>
            </div>                   
            <div class="form-group col-md-4">
              <label for="id_categoria">Categoria</label>
              <select class="form-control" id="id_categoria" name="id_categoria">
                <option value="" selected disabled>ELIGE UNA OPCIÓN</option>
              </select>
            </div>  
            <div class="col-md-4">
              <div class="form-group">
                <label for="costo" class="control-label">Costo</label>
                <input type="text" class="form-control modal-clientes" id="costo" name="costo">
              </div>
            </div>   
            <div class="col-md-4">
              <div class="form-group">
                <label for="unidad" class="control-label">Unidad</label>
                <input type="text" class="form-control modal-clientes" id="unidad" name="unidad">
              </div>
            </div>
            <div class="form-group col-md-4">
              <label for="id_estatus">Estatus</label>
              <select class="form-control" id="id_estatus" name="id_estatus">
              <option value="" selected disabled>ELIGE UNA OPCIÓN</option>              
              </select>
            </div>                                                       
            <!--/div-->                                                                      
          </div>         
        </form>        
      </div>
      <div class="modal-footer">
        <button id="cancelar" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button id="nuevomaterial" type="submit" class="btn btn-primary">Nuevo</button>
        <button id="actualizarmaterial" type="button" class="btn btn-primary">Actualizar</button>
      </div>
    </div>
  </div>
</div>

<script>

$.ajax({
  dataType: "json",
  url: 'llenarcombocategoriasmateriales',
  type: "POST",
  success: function(data){
    $('select[name="id_categoria"]').append(data);
    $('select[name="id_categoria"]>option').removeAttr("selected");
  }
});

$.ajax({
  dataType: "json",
  url: 'llenarcomboproveedores',
  type: "POST",
  success: function(data){
    $('select[name="id_cli-prov"]').append(data);
    $('select[name="id_cli-prov"]>option').removeAttr("selected");
  }
});

$.ajax({
  dataType: "json",
  url: 'llenarcombotiposestatus',
  async: false,
          //type: "POST",
          success: function(data){
            $('select[name="id_estatus"]').append(data);
            $('select[name="id_estatus"]>option').removeAttr("selected");
          }
        });

$(document).ready(function(){

var catMateriales = $('#catMateriales').DataTable({
  ajax:{
    url: 'consultarmateriales'
  },  
    //"info" : false,
    //"searching": false,
    "paging":    false,
    "scrollY":   '58vh',
    //"scrollX": true 
    dom: 'Blfrtip',
    buttons: [
    'excel'
    ],      
    "columns":[
    {data:"id_material"},
    {data:"clave"},
    {data:"descripcion"},
    {data:"id_cli-prov"},
    {data:"id_categoria"},
    {data:"costo"},
    {data:"unidad"},
    {data:"id_estatus"},
    {data:"detalle"}
    ],  
    "columnDefs": [
    {
      "className": "dt-center",
      "targets": [3,4,5,6,7,8]
    },
    ]         
  }); 

$( ".buttons-excel" ).hide(); 
$( "#excel-materiales" ).on( "click", function() {
  $( ".buttons-excel" ).trigger( "click" );
});   

$('#catMateriales').on("click", "a.btn-detalles", function () 
{
  $("#nuevomaterial").hide();
  $("#actualizarmaterial").show();
  var data = catMateriales.row($(this).parents("tr")).data();
  idmaterial = data.id_material;
  $.post('extraermaterial', {idmaterial:idmaterial},
    function(result)
    {
      console.log(result.id_cliprov);       
      $("#clave").val(result.clave);
      $("#descripcion").val(result.descripcion);  
      $('select[name="id_cli-prov"]>option[value="'+result.id_cliprov+'"]').attr("selected", true);      
      $('select[name="id_categoria"]>option[value="'+result.id_categoria+'"]').attr("selected", true);      
      $("#costo").val(result.costo);
      $("#unidad").val(result.unidad);
      $('select[name="id_estatus"]>option[value="'+result.id_estatus+'"]').attr("selected", true);      
      $("#detalleModal").modal('show'); 
    },'json'
    );

});

$("#actualizarmaterial").click(function(){
  var cadena = $("#frmactualizarmaterial").serialize()+'&id_material='+idmaterial;
  console.log(cadena);
  $.post('actualizarmaterial', cadena,
    function(result)
    {
      swal("Actualizado","success");
      $("#detalleModal").modal('hide');
      catMateriales.ajax.reload();
    },'json'
    );
});

$("#btnnuevomaterial").click(function(){
  $("#actualizarmaterial").hide();
  $("#nuevomaterial").show();   
  $("#clave").val("");
  $("textarea#descripcion").val("");  
  $("select[id=id_cli-prov]").val("0");   
  $("select[id=categoria]").val("0");
  $('#id_cli-prov').val($('#id_cli-prov > option:first').val());
  $('#id_categoria').val($('#id_categoria > option:first').val());
  $('#id_estatus').val($('#id_estatus > option:first').val());
  $("#costo").val("");
  $("#unidad").val("");
  $("select[id=id_estatus]").val("0");
});

$("#nuevomaterial").click(function(){
  var cadena = $("#frmactualizarmaterial").serialize();
  console.log(cadena);
  $.post('insertarmaterial', cadena,
    function(result)
    {
      swal("Se registro","success");
      $("#detalleModal").modal('hide');
      catMateriales.ajax.reload();
    },'json'
    );    
});
});
</script>    