<div class="col-md-4 col-md-offset-4" id="card-login">

    <div id="panel">
        <div class="panel panel-default">
            <div style="padding:  30px 100px 10px 100px;">
                <center>
                    <img  id="logoLogin" class="img-responsive" src="images/logo.png" />
                </center>
            </div>
            <div class="panel-body">
                <h3 style="text-align: center;">Iniciar sesión</h3>
                <hr>
                <form name="login" id="login" method="POST" class="form-horizontal">
                    <div class="form-group">
                        <label for="Usuario" class="control-label col-sm-5" style="text-align: left;">Usuario: <span class="color-red">&#42;</span></label>
                        <div class="col-sm-7">
                            <input type="text" name="usuario" id="usuario" class="form-control" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="control-label col-sm-5" style="text-align: left;">Contrase&ntilde;a: <span class="color-red">&#42;</span></label>
                        <div class="col-sm-7">
                            <input type="password" name="password" id="password" class="form-control" required/>
                        </div>
                    </div>
                    <div>
                        <center>
                            <input type="submit" class="btn btn-default" name="login" id="login" value="Entrar   &#9658;" style="width: 100%;">
                        </center>
                        <div id="errorLogin"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!--div id="divlogin">
        <img  id="logoLogin" class="img-responsive" src="images/logo.png" />
        <form name="login" id="login" method="POST" class="form-horizontal">
            <br/>
            <div class="form-group">
                <label for="Usuario" class="control-label col-sm-3">Usuario: <span class="color-red">&#42;</span></label>
                <div class="col-sm-9">
                    <input type="text" name="usuario" id="usuario" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="control-label col-sm-3">Contrase&ntilde;a: <span class="color-red">&#42;</span></label>
                <div class="col-sm-9">
                    <input type="password" name="password" id="password" class="form-control" required/>
                </div>
            </div>
            <br/>
            <div>
                <center>
                    <input type="submit" class="btn" name="login" id="login" value="Entrar   &#9658;">
                </center>
                <div id="errorLogin"></div>
            </div>
        </form>
    </div-->
</div>
<script>
    document.body.style.backgroundColor = '#bfa276';
</script>