<?php echo $this->doctype() ?>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php 
  $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8');
  $this->headLink()->appendStylesheet($this->baseUrl('css/bootstrap/bootstrap.min.css'));
  $this->headLink()->appendStylesheet($this->baseUrl('css/estilo.css'));
  $this->headLink()->appendStylesheet($this->baseUrl('css/jquery.dataTables.min.css'));
  $this->headLink()->appendStylesheet($this->baseUrl('font-awesome4.2.0/css/font-awesome.min.css'));
  $this->headLink()->appendStylesheet($this->baseUrl('css/ds-digital.css'));
  $this->headLink()->appendStylesheet($this->baseUrl('css/estilos.produccion.css'));
  /*$this->headLink()->appendStylesheet($this->baseUrl('css/estilos_txt.css'));  
  $this->headLink()->appendStylesheet($this->baseUrl('css/buttons.dataTables.min.css'));
  $this->headLink()->appendStylesheet($this->baseUrl('css/theme.blue.css'));*/
  $this->headScript()->prependFile($this->baseUrl('js/jquery-1.12.3.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/bootstrap/bootstrap.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/script.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/jquery.dataTables.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/dataTables.buttons.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/buttons.flash.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/jszip.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/pdfmake.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/vfs_fonts.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/buttons.html5.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/buttons.print.min.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/grids.js'), 'text/javascript');
  $this->headScript()->appendFile($this->baseUrl('js/guardarClientes.js'), 'text/javascript');
  //$this->headScript()->appendFile($this->baseUrl('js/gridsProduccion.js'), 'text/javascript');
  //$this->headScript()->appendFile($this->baseUrl('js/gridsCatalogos.js'), 'text/javascript');

  $this->headTitle()->append('Miapp/Corrugados');
  echo $this->headMeta();
  echo $this->headTitle(); 
  echo $this->headLink();
  echo $this->headScript();

  ?>
  <!--Currency-->
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/currency/css/currency.css">
  <script src="<?php echo $this->baseUrl(); ?>/currency/js/currency.js"></script>
  <!--Currency-->
  <!--tabindex-->
  <script src="<?php echo $this->baseUrl(); ?>/tabindex/tabindex.js"></script>
  <!--tabindex-->
  <!--jQuery Sweet Alert-->
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/sweetalert/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl(); ?>/sweetalert/js/sweetalert.min.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/js/typeahead.js"></script>

  <script type="text/javascript">

  $(document).ready(function()
  {

    localStorage.user = "<?php $usuario = Zend_Auth::getInstance()->getIdentity(); echo $usuario->id_usuario; ?>";

    var errores = sessionStorage.getItem("id");

    if(errores!="")
    {
      $("#notificaciones").html("Consulta exitosa");
    }
    else
    {
      $("#notificaciones").html("Error de consulta");
    }

    function mueveReloj(){
      momentoActual = new Date();
      hora = momentoActual.getHours();
      minuto = momentoActual.getMinutes();
      segundo = momentoActual.getSeconds();
      if(segundo<10)
      {
        segundo="0"+segundo;
      }
      if(minuto<10)
      {
        minuto="0"+minuto;
      }
      horaImprimible = hora + " : " + minuto + " : " + segundo;
      $("#hora").html(horaImprimible);
    }
    setInterval (function() {mueveReloj();}, 500);

  });
  </script>
</head>
<body>

  <header>

    <div class="logo-resize">
     <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/logo.png"></a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <img  class="img-right" src="<?php echo $this->baseUrl(); ?>/images/f_header.png">
        </ul>
      </div>
    </nav> 
  </div>
</header>

<?php   
$front =Zend_Controller_Front :: getInstance ();  
$baseUrl = $front -> getBaseUrl (); 
?>

<?php $menu = Zend_Auth::getInstance()->getIdentity();?>
<main>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 menu">
        <div style="position: fixed;">
          <div class="nav-side-menu">
            <div class="brand">PANEL DE CONTROL</div>
            <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
            <div class="menu-list">
              <ul id="menu-content" class="menu-content collapse out">
                <?php if($menu->mnuproduccion_ordenproduccion == 1) { ?>                
                <li  data-toggle="collapse" data-target="#products" class="collapsed">
                  <a href="#"><i class="glyphicon glyphicon-list-alt"></i> Ordenes<span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                  <!--li><a href="<?php //echo $baseUrl;?>/Ordenes/show">Nueva</a></li-->
                  <li><a href="<?php echo $baseUrl;?>/ordenes/activas">Activas</a></li>
                  <li><a href="<?php echo $baseUrl;?>/ordenes/canceladas">Canceladas</a></li>
                  <li><a href="<?php echo $baseUrl;?>/ordenes/finalizadas">Finalizadas</a></li>
                  <li><a href="#!">Estatus de Ordenes</a></li>
                  <!--li><a href="#">Imprimir</a></li-->
                </ul>
                <?php } ?>
                <?php if($menu->mnuproduccion == 1) { ?>
                <li data-toggle="collapse" data-target="#produccion" class="collapsed">
                  <a href="#"><i class="fa fa-cog fa-lg"></i> Producción<span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="produccion">
                  <?php if($menu->mnuproduccion_caiman == 1) { ?>
                  <li><a href="<?php echo $baseUrl;?>/produccion/ranurado">Ranurado</a></li>
                  <?php } ?>
                  <?php if($menu->mnuproduccion_refiladora == 1) { ?>
                  <li><a href="<?php echo $baseUrl;?>/produccion/refilado">Refilado</a></li>
                  <?php } ?>
                  <?php if($menu->mnuproduccion_flexografica == 1) { ?>
                  <li><a href="<?php echo $baseUrl;?>/produccion/flexoranurado">Flexo Ranurado</a></li>
                  <?php } ?>
                  <?php if($menu->mnuproduccion_pegadoracorrugados == 1) { ?>  
                  <li><a href="<?php echo $baseUrl;?>/produccion/pegadodecorrugado">Pegado de Corrugado</a></li>
                  <?php } ?>
                  <?php if($menu->mnuproduccion_empalme == 1) { ?>  
                  <li><a href="<?php echo $baseUrl;?>/produccion/empalmado">Empalmado</a></li>
                  <?php } ?>
                  <?php if($menu->mnuproduccion_suajado == 1) { ?>
                  <li><a href="<?php echo $baseUrl;?>/produccion/suajado">Suajado</a></li>
                  <?php } ?>
                  <?php if($menu->mnuproduccion_pegadolineal == 1) { ?>  
                  <li><a href="<?php echo $baseUrl;?>/produccion/pegado">Pegado</a></li>
                  <?php } ?>                   
                </ul>
                <?php } ?>
                <?php if($menu->mnualmacen == 1) { ?>                
                <li data-toggle="collapse" data-target="#almacen" class="collapsed">
                  <a href="#"><i class="fa fa-dropbox fa-lg"></i> Almacen</a><span class="arrow"></span>
                </li>
                <ul class="sub-menu collapse" id="almacen">
                  <?php if($menu->mnualmacen_kardex == 1) { ?>
                  <li><a href="<?php echo $baseUrl;?>/Kardex/show">Kardex</a></li>
                  <?php } ?>
                  <?php if($menu->mnualmacen_ordencompra == 1) { ?>
                  <li><a href="#!">Orden de compra</a></li>
                  <?php } ?>
                </ul>
                <?php } ?>
                <?php if($menu->mnuventas == 1) { ?>
                <li data-toggle="collapse" class="collapsed"><!--data-target="#service"-->
                  <a href="#!"><i class="glyphicon glyphicon-usd"></i>Cotizador<span class="arrow"></span></a>
                </li>  
                <ul class="sub-menu collapse" id="service">                                    
                  <li><a href="<?php echo $baseUrl;?>/Cotizador">Orden de producción</a></li>
                  <?php if($menu->mnuventas_cotizaciones_maquilas == 1) { ?>
                  <li><a href="<?php echo $baseUrl;?>/cotizador/maquilas">Cotizador de Maqulias</a></li>
                  <?php } ?>
                  <li>Imprimir</li>
                </ul>
                <?php } ?>
                <?php if($menu->mnucatalogos == 1) { ?>                              
                  <li data-toggle="collapse" data-target="#service2" class="collapsed">
                    <a href="#"><i class="fa fa-globe fa-lg"></i>Catálogos<span class="arrow"></span></a>
                  </li>                  
                  <ul class="sub-menu collapse" id="service2">
                    <?php if($menu->mnucatalogos_clientes == 1) { ?>                  
                    <!--li><a href="<?php //echo $baseUrl;?>/index/clientes">Clientes</a></li-->
                    <li><a href="<?php echo $baseUrl;?>/catalogos/clientes">Clientes</a></li>
                    <?php } ?>
                    <?php if($menu->mnucatalogos_proveedores == 1) { ?>                                    
                    <!--li><a href="<?php //echo $baseUrl;?>/index/proveedores">Proveedores</a></li-->
                    <li><a href="<?php echo $baseUrl;?>/catalogos/proveedores">Proveedores</a></li>
                    <?php } ?> 
                    <!--li><a href="<?php //echo $baseUrl;?>/index/articulos">Artículos</a></li-->
                    <?php if($menu->mnucatalogos_materiales == 1) { ?>
                    <!--li><a href="<?php //echo $baseUrl;?>/index/materiales">Materiales</a></li-->
                    <li><a href="<?php echo $baseUrl;?>/catalogos/materiales">Materiales</a></li>
                    <?php } ?>
                    <!--li><a href="<?php //echo $baseUrl;?>/index/maquinas">Máquinas</a></li-->
                    <?php if($menu->mnucatalogos_usuarios == 1) { ?>
                    <!--li><a href="<?php //echo $baseUrl;?>/index/usuario">Usuarios</a></li-->
                    <li><a href="<?php echo $baseUrl;?>/catalogos/usuarios">Usuarios</a></li>
                    <?php } ?>
                  </ul>
                <?php } ?>                
                <li>
                  <a href="<?php echo $baseUrl;?>/Login/salir">
                    <i class="glyphicon glyphicon-log-out"></i>Salir
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-10">
        <?= $this->layout()->content;?>
      </div>
    </div>
  </div>
</main>
<footer>
  <div class="container">
    <div class="row footer">
      <div id="notificaciones" class="col-md-3 vcenter">Error de consutla</div>
      <div id="usr" class="col-md-3 vcenter">Sesión de: <?php $usuario = Zend_Auth::getInstance()->getIdentity(); echo $usuario->nombre; ?></div>
      <div id="fecha" class="col-md-2 vcenter"><?php echo date("d-m-Y"); ?></div>
      <div id="hora" class="col-md-2 vcenter"></div>
      <div class="col-md-2 vcenter">Version 1.1</div>
    </div> 
  </div>
</footer>
</body>
</html>