<div class="row">
	<div class="col-md-9">
		<button id="btn-nueva" class="btn btn-primary">Nueva</button>
		<button id="btn-recuperar" class="btn btn-primary">Recuperar</button>
		<a class="btn btn-primary" href="http://localhost/Corrugados/public/ordenes/orderpdf?Id=16" role="button" id="btn-imprimir" target="FormatoPDF">Imprimir</a>
	</div>		
	<div class="col-md-3"><h1><?php  echo $this->titulo; echo @$this->nombreCliente?></h1></div>
</div>
<div class="row">
	<div class="col-md-12 padding-right-15">
		<div class="row">
			<div class="col-md-12">
				<table id="ordFinalizadas" class="compact cell-border" cellspacing="0" width="100%" style="text-align: center;">
					<thead>
						<tr>
							<th>IdOrden</th>
							<th>Nombre Trabajo</th>
							<th>Estatus</th>
							<th>Cant_requerida</th>
							<th>Cant_liberada</th>
							<th>Cant_merma</th>
							<th>Cant_producida</th>
							<th>Fecha Entrega</th>
						</tr>
					</thead>
					<tbody>
						<!--Registro de la BD-->
					</tbody>
				</table>				
			</div>
		</div>		  		
	</div>
</div>

<script>

	$("#btn-nueva").attr('disabled', false);
	$("#btn-recuperar").attr('disabled', true);
	$("#btn-imprimir").attr('disabled', true);

	var ordFinalizadas = $('#ordFinalizadas').DataTable({
		ajax:{
			url: 'consultarfinalizadas'
		}, 	
		"columns":[
		{data:"numorden",width:"5%"},
		{data:"trabajo"},
		{data:"estatus",width:"10%"},
		{data:"cant_requerida",width:"10%"},
		{data:"cant_liberada",width:"10%"},
		{data:"cant_merma",width:"10%"},
		{data:"cant_producida",width:"10%"},

		{data:"fecha_entrega",width:"10%"}
		],
		"columnDefs": 
		[
		{"className": "dt-body-left", "targets": [1]},
		{"className": "dt-head-center", "targets": "_all"}
		],	
		"order": [[0, "desc" ]],
		"searching": true,
		"paging":    false,
		"scrollY":   '320px',
		"scrollX": true			
	});

	$('#ordFinalizadas tbody').on( 'click', 'tr', function () {
		if ( $(this).hasClass('selected') ) {
			$(this).removeClass('selected');
			$("#btn-nueva").attr('disabled', false);
			$("#btn-recuperar").attr('disabled', true);
			$("#btn-imprimir").attr('disabled', true);
		}
		else {
			ordFinalizadas.$('tr.selected').removeClass('selected');
			$(this).addClass('selected');
			$("#btn-nueva").attr('disabled', true);
			$("#btn-recuperar").attr('disabled', false);
			$("#btn-imprimir").attr('disabled', false);

		}

		var id = $(this).find('td').eq(0).html();

		$("#btn-recuperar").click(function(){

			window.location.href = "show?ID="+id+"&Tipo=2&Estatus=finalizadas";

		});

		$("a[id='btn-imprimir']").attr('href', 'orderpdf?Id='+id);

		return false;

	});

	$("#btn-nueva").click(function(){

		window.location.href = "show?ID=0&Tipo=1&Estatus=finalizadas";

	});



</script>