<?php 
$this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css');
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js','text/javascript');
?>


<style>
input[type=date]::-webkit-outer-spin-button,
input[type=date]::-webkit-inner-spin-button {

  -webkit-appearance: none;
  margin: 0;

}

input[type=date] {

  -moz-appearance:textfield;

}

.helper {

  margin-top: -19px;
  margin-bottom: 0px;
  font-size: 12px;

}

.bs-panel-interno{

  margin-bottom: 0px;

}

h4.bs-titulo {

  font-size: 14px;
  font-weight: bold;

}

.bs-titulo {

  margin-top: -10px;
  padding-left: 5px;
  margin-bottom: 0px;

}

.bs-titulo span {

  background-color: white;
  padding: 0 8px 0 8px;

}

.bs-body{

  padding: 0 10px 0 10px;

}

.bs-sm{

  width: 70px !important;

}

.bs-md{

  width: 100px !important;

}

label{

  font-size: 13px;

}

.Folio{
  font-size: 1.5em;
  color: red;
}

.helper-left{
  padding-left: 0px;
}

</style>




<form id="OrdenProduccion">

  <div class="row">

   <div class="col-md-3">

    <p class="Folio">Folio OP: <span class="num_folio" id="IdOrden">por asignar</span></p>

  </div>

  <div class="col-md-3">

   <div class="form-horizontal">

     <div class="form-group">

       <label for="inputtext3" class="col-md-6 control-label">Folio OC prov:</label>

       <div class="col-md-6">
        <input type="text" class="form-control input-sm" id="id_ordenmaterial" name="id_ordenmaterial">
      </div>

    </div>

  </div>



</div>

<div class="col-md-6">
  <h1 style="margin-top: 5px;"><?php  echo $this->titulo; echo @$this->nombreCliente?></h1>
</div>

</div>



<div class="row">

 <div class="col-md-6">

   <div class="form-horizontal">

     <div class="form-group">

       <label for="id_cliente" class="col-md-2 control-label">Cliente:</label>

       <div class="col-md-10">

        <select class="selectpicker form-control input-sm" id="id_cliente" name="id_cliente" data-live-search="true"></select>

      </div>

    </div>

  </div>

</div>

<div class="col-md-3">

 <div class="form-horizontal">

   <div class="form-group">

     <label for="inputtext3" class="col-md-6 control-label">F. OC Cliente:</label>

     <div class="col-md-6">

      <input type="text" class="form-control input-sm" id="id_ordencompra" name="id_ordencompra">

    </div>

  </div>

</div>

</div>

<div class="col-md-3">

 <div class="form-horizontal">

   <div class="form-group">

     <label for="inputtext3" class="col-md-6 control-label">Fecha registro:</label>

     <div class="col-md-6">

      <input type="date" class="form-control input-sm date-cls" id="fecha_emision" name="fecha_emision" value="<?php echo date("Y-m-d");?>" readonly>

    </div>

  </div>

</div>

</div>

</div>



<div class="row">

 <div class="col-md-6">

   <div class="form-horizontal">

     <div class="form-group">

       <label for="inputtext3" class="col-md-2 control-label">Trabajo:</label>

       <div class="col-md-10">

        <input type="text" class="form-control input-sm" id="nombre_trabajo" name="nombre_trabajo">

      </div>

    </div>

  </div>

</div>

<div class="col-md-3">

 <div class="form-horizontal">

   <div class="form-group">

     <label for="inputtext3" class="col-md-6 control-label">F. cotización:</label>

     <div class="col-md-6">

      <input type="text" class="form-control input-sm" id="id_cotizacion" name="id_cotizacion">

    </div>

  </div>

</div>

</div>

<div class="col-md-3">

 <div class="form-horizontal">

   <div class="form-group">

     <label for="inputtext3" class="col-md-6 control-label">Fecha entrega:</label>

     <div class="col-md-6">

      <input type="date" class="form-control input-sm date-cls" id="fecha_requeridaentrega" name="fecha_requeridaentrega" >

    </div>

  </div>

</div>

</div>

</div>

<br>



<div class="row">

  <!--div class="col-md-3">



    <div class="form-horizontal">

      <div class="form-group">

        <label for="inputtext3" class="col-md-4 control-label">C. requerida</label>

        <div class="col-md-2">

          <input type="text" class="form-control input-sm" id="cant_requerida" name="cant_requerida">

        </div>

      </div>

    </div>
    <div class="form-horizontal">

      <div class="form-group">

        <label for="inputtext3" class="col-md-4 control-label">Merma</label>

        <div class="col-md-2">

          <input type="text" class="form-control input-sm" id="cant_requerida" name="cant_requerida">

        </div>

      </div>

    </div>
  </div -->

  <div class="col-md-3">

   <div class="form-horizontal">

     <div class="form-group">

      <label class="col-sm-4 control-label">Cantidad:</label>

      <div class="col-sm-4">

        <span class="help-block helper">Requerida</span>

        <input type="text" class="form-control input-sm" id="cant_requerida" name="cant_requerida">

      </div>

      <div class="col-sm-4 ">

        <span class="help-block helper">Merma</span>

        <input type="text" class="form-control input-sm" id="cant_cmerma" name="cant_cmerma" >

      </div>

    </div>

  </div>

</div>

<div class="col-md-4">

 <div class="form-horizontal">

   <div class="form-group">

    <label class="col-sm-3 control-label">M. Final:</label>

     <div class="col-sm-3">

      <span class="help-block helper">Frente</span>

      <input type="text" class="form-control input-sm" id="med_frente" name="med_frente">

    </div>

    <div class="col-sm-3">

      <span class="help-block helper">Fondo</span>

      <input type="text" class="form-control input-sm" id="med_fondo" name="med_fondo" >

    </div>

    <div class="col-sm-3">

      <span class="help-block helper">Alto</span>

      <input type="text" class="form-control input-sm" id="med_alto" name="med_alto" >

    </div>

  </div>

</div>

</div>

<div class="col-md-2">

 <div class="row">

   <div class="radio">

     <label class="radio-inline">

      <input type="radio" id="mcaja" name="tipo_medida" value="option1"> M. Caja

    </label>

    <label class="radio-inline">

      <input type="radio" id="mcarton" name="tipo_medida" value="option2"> M. Carton

    </label>

  </div>

</div>

</div>

<div class="col-md-1">

 <span class="help-block helper">Largo</span>
 <input type="text" class="form-control input-sm" id="med_largo" name="med_largo"/>

</div>



<div class="col-md-1">

 <span class="help-block helper">Ancho</span>
 <input type="text" class="form-control input-sm" id="med_ancho" name="med_ancho">

</div>


<div class="col-md-1">

 <span class="help-block helper">Med. req</span>
 <input type="text" class="form-control input-sm" id="med_requerido" readonly>

</div>

</div>

<div class="row">

 <div class="col-md-5">

   <div class="form-horizontal">

     <div class="form-group">

       <label for="articulo" class="col-md-3 control-label">Articulo:</label>

       <div class="col-md-9">

        <select class="form-control input-sm" id="articulo" name="articulo">
          <option value="null" selected=>SELECCIONAR</option>
        </select>

      </div>

    </div>

  </div>

  <div class="form-horizontal">

   <div class="form-group">

     <label for="tipo_producto" class="col-md-3 control-label">Producto:</label>

     <div class="col-md-9">

      <select class="form-control input-sm" id="tipo_producto" name="tipo_producto">
        <option value="null">SELECCIONAR</option>
      </select>

    </div>

  </div>

</div>

</div>

<div class="col-md-7">

 <div class="panel panel-default">

   <h4 class="bs-titulo"><span>Material</span></h4>

   <div class="panel-body bs-body">

     <div class="col-md-3">

      <div class="radio">

        <label><input type="radio" id="mat-corrugados" name="selector_material" value="8">Corrugados</label>

      </div>

      <div class="radio">

        <label><input type="radio" id="mat-kaples" name="selector_material" value="9">Kaples y sulfatadas</label>

      </div>

    </div>

    <div class="col-md-9" style="margin-top: 10px;">

      <div class="form-horizontal">

        <div class="form-group">

          <label for="tipo_material" class="col-md-3 control-label">Tipo:</label>

          <div class="col-md-9">

            <select class="form-control input-sm" id="tipo_material" name="tipo_material">

              <option value="null">SELECCIONAR</option>

            </select>

          </div>

        </div>

      </div>

      <div class="form-horizontal">

        <div class="form-group">

          <label for="carton" class="col-md-3 control-label">Carton:</label>

          <div class="col-md-9">

            <select class="form-control input-sm" id="carton" name="carton">

             <option value="null" selected>SELECCIONAR</option>

           </select>

         </div>

       </div>

     </div>

     <div class="form-horizontal">

      <div class="form-group">

        <label for="tam-carton" class="col-md-3 control-label">Tamaño:</label>

        <div class="col-md-9">

          <select class="form-control input-sm" id="tam-carton" name="tam-carton">

           <option value="null" selected>SELECCIONAR</option>

         </select>

       </div>

     </div>

   </div>

 </div>

</div>

</div>

</div>

</div>

<div class="row">

 <div class="col-md-6">

   <div class="panel panel-default">

     <div class="bs-titulo">

       <h4 class="bs-titulo"><span>Suajado</span></h4>

     </div>

     <div class="panel-body">

       <div class="row">

        <div class="col-md-6">

          <div class="panel panel-default bs-panel-interno">

            <h5 class="bs-titulo"><span>Maquina</span></h5>

            <div class="panel-body bs-body">

              <div class="radio">

               <label><input type="radio" id="maq-automatica" name="maquina_suajado" value="7" data-maquina="SUAJADORA AUTOMATICA" data-proceso="1">Automatica</label>

             </div>

             <div class="radio">

               <label><input type="radio" id="maq-quijada1" name="maquina_suajado" value="8" data-maquina="SUAJADORA QUIJADA 1" data-proceso="1" >Quijada 1</label>

             </div>

             <div class="radio">

               <label><input type="radio" id="maq-quijada2" name="maquina_suajado" value="9" data-maquina="SUAJADORA QUIJADA 2" data-proceso="1" >Quijada 2</label>

             </div>

             <div class="radio">

               <label><input type="radio" id="maq-plana" name="maquina_suajado" value="10" data-maquina="SUAJADORA PLANA" data-proceso="1">Plana</label>

             </div>

             <div class="radio">

              <label><input type="radio" id="maq-plana" name="maquina_suajado" value="16" data-maquina="SUAJADORA DE RODILLO" data-proceso="1">De rodillo</label>

            </div>

          </div>

        </div>

      </div>

      <div class="col-md-6">

        <div class="form-horizontal">

          <div class="form-group">

            <label for="med_suaje" class="col-md-6 control-label">Medida lineal:</label>

            <div class="col-md-6">

             <input type="text" class="form-control input-sm" id="med_suaje" name="med_suaje" >

           </div>

         </div>

       </div>

       <div class="form-horizontal">

        <div class="form-group">

          <label for="med_cito" class="col-md-6 control-label">Medida cito:</label>

          <div class="col-md-6">

           <input type="text" class="form-control input-sm" id="med_cito" name="med_cito" >

         </div>

       </div>

     </div>

     <div class="form-horizontal">

      <div class="form-group">

        <label for="tipo_desbarbe" class="col-md-6 control-label">Desbarbe:</label>

        <div class="col-md-6">

         <input type="text" class="form-control input-sm" id="tipo_desbarbe" name="tipo_desbarbe">

       </div>

     </div>

   </div>

 </div>

</div>

</div>

</div>

<div class="panel panel-default">

 <h4 class="bs-titulo"><span>Pegado</span></h4>

 <div class="panel-body">

   <div class="row">

    <div class="col-md-12">

      <div class="panel panel-default bs-panel-interno">

        <h5 class="bs-titulo"><span>Maquina</span></h5>

        <div class="panel-body bs-body">

          <div class="col-md-6">



           <div class="radio">

             <label><input type="radio" id="pegado-cajas" name="tipo_pegado" value="4" data-maquina="PEGADORA CORRUGADOS" data-proceso="3" data-cvepega = 'UNIVM  5298'>Pegadora de cajas</label>

             <label><input type="radio" id="pegado-chica" name="tipo_pegado" value="12" data-maquina="PEGADORA LINEAL CHICA" data-proceso="2" data-cvepega = 'TILMEX 1126'>Pegadora lineal chica</label>

           </div>

         </div>



         <div class="col-md-6">

           <div class="radio">

             <label><input type="radio" id="pegado-grande" name="tipo_pegado" value="11" data-maquina="PEGADORA LINEAL GRANDE" data-proceso="2" data-cvepega = 'TILMEX 1129'>Pegadora lineal grande</label>

             <label><input type="radio" id="pegado-manual" name="tipo_pegado" value="13" data-maquina="PEGADO MANUAL" data-proceso="2" data-cvepega = ''>Pegado Manual</label>

           </div>

         </div>



       </div>

     </div>

   </div>



   <div class="col-md-12">

    <br>

    <div class="col-md-4">

      <div class="checkbox">

       <label><input type="checkbox" value="1" name="predoblado" id="predoblado">Predoblado</label>

     </div>

   </div>

   <div class="col-md-8">

    <div class="form-horizontal">

      <div class="form-group">

       <label for="clave_pegamento" class="col-md-6 control-label" style="text-align: left;">

         Clave pegamento:

       </label>

       <div class="col-md-6">

         <input type="text" class="form-control input-sm" id="clave_pegamento" name="clave_pegamento">

       </div>

     </div>

   </div>

 </div>

 

</div>

<div class="col-md-12">

  <div class="panel panel-default">

    <div class="panel-body">

      <div class="col-md-12">

       <center>

         <label class="radio-inline"><input type="radio" id="pegado-disco" name="pegado_con" value="1">Con disco</label>

         <label class="radio-inline"><input type="radio" id="pegado-inyector" name="pegado_con" value="2">Con inyector</label>

       </center>

     </div>

   </div>

 </div>

</div>



<div class="col-md-12">

  <div class="panel panel-default" style="margin-bottom: 2px;">

    <div class="panel-body bs-body">

      <div class="form-inline">

       <center>

         <div class="checkbox">

           <label><input type="checkbox" value="15" name="grapado" data-maquina="ENGRAPADORA" data-proceso="9"> Grapado</label>

         </div>

         <div class="form-group" style="margin: 10px 0 10px 100px;">

           <label for="text">Núm. grapas:</label>
           <input type="text" class="form-control input-sm" id="num_grapas" name="num_grapas">

         </div>

       </center>

     </div>

   </div>

 </div>

</div>

</div>

</div>

</div>

<div class="row">
  <div class="col-md-12">
   <div class="panel panel-default">

    <h4 class="bs-titulo"><span>Entrega</span></h4>

    <div class="panel-body">

      <div class="row">

        <div class="col-md-6">

          <label class="radio-inline"><input type="radio" id="ent-total" name="tipo_entrega" value="TOTAL">Total</label>

        </div>

        <div class="col-md-6">

          <label class="radio-inline"><input type="radio" id="ent-parcial" name="tipo_entrega" value="PARCIAL">Parcial</label>

        </div>

      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-md-3">
          <span class="help-block helper">Parcial 1</span>
          <input type="text" class="form-control input-sm " id="cant_parc1" name="cant_parc1" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc1" name="fecparc1" >
        </div>
        <div class="col-md-3">
          <span class="help-block helper">Parcial 5</span>
          <input type="text" class="form-control input-sm" id="cant_parc5" name="cant_parc5" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc5" name="fecparc5" >
        </div>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-md-3">
          <span class="help-block helper">Parcial 2</span>
          <input type="text" class="form-control input-sm" id="cant_parc2" name="cant_parc2" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc2" name="fecparc2" >
        </div>
        <div class="col-md-3">
          <span class="help-block helper">Parcial 6</span>
          <input type="text" class="form-control input-sm" id="cant_parc6" name="cant_parc6" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc6" name="fecparc6" >
        </div>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-md-3">
          <span class="help-block helper">Parcial 3</span>
          <input type="text" class="form-control input-sm" id="cant_parc3" name="cant_parc3" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc3" name="fecparc3" >
        </div>
        <div class="col-md-3">
          <span class="help-block helper">Parcial 7</span>
          <input type="text" class="form-control input-sm" id="cant_parc7" name="cant_parc7" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc7" name="fecparc7" >
        </div>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-md-3">
          <span class="help-block helper">Parcial 4</span>
          <input type="text" class="form-control input-sm" id="cant_parc4" name="cant_parc4" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc4" name="fecparc4" >
        </div>
        <div class="col-md-3">
          <span class="help-block helper">Parcial 8</span>
          <input type="text" class="form-control input-sm" id="cant_parc8" name="cant_parc8" >
        </div>
        <div class="col-md-3 helper-left">
          <span class="help-block helper">Fecha</span>
          <input type="date" class="form-control input-sm" id="fecparc8" name="fecparc8" >
        </div>
      </div>

    </div>

  </div>

</div>
</div>

</div>



<div class="col-md-6">

 <div class="panel panel-default">

   <h4 class="bs-titulo"><span>Ranurado</span></h4>

   <div class="panel-body">

     <label>Maquina:&nbsp;&nbsp;</label>

     <label class="radio-inline"><input type="radio" id="maq-flexografica" name="maquina_ranurado" value="3" data-maquina="FLEXOGRAFICA" data-proceso="4">Flexografica</label>

     <label class="radio-inline"><input type="radio" id="maq-caiman" name="maquina_ranurado" value="1" data-maquina="CAIMAN" data-proceso="4">Caiman</label>

   </div>

 </div>

 <div class="panel panel-default">

   <h4 class="bs-titulo"><span>Refiladora</span></h4>

   <div class="panel-body">

     <label>Proceso:&nbsp;&nbsp;</label>

     <label class="radio-inline"><input type="radio" name="proceso_refilado" id="maq-refilado" value="6" data-maquina="REFILADORA" data-proceso="6">Refilado</label>

     <label class="radio-inline"><input type="radio" name="proceso_refilado" id="maq-rayado" value="5" data-maquina="REFILADORA" data-proceso="5">Rayado</label>

     <label class="radio-inline"><input type="radio" name="proceso_refilado" id="maq-refilado-rayado" value="7" data-maquina="REFILADORA" data-proceso="7">Refilado + Rayado</label>

   </div>

 </div>

 <div class="panel panel-default">

   <h4 class="bs-titulo"><span>Empalme</span></h4>

   <div class="panel-body">

     <label>Maquina:&nbsp;&nbsp;</label>

     <label class="radio-inline"><input type="radio" id="maq-auto" name="maquina_empalme" value="5" data-maquina="EMPALMADORA AUTOMATICA" data-proceso="10" data-cvepega = 'UNIVM  5435'>Automatica</label>

     <label class="radio-inline"><input type="radio" id="maq-semi" name="maquina_empalme" value="6" data-maquina="EMPALMADORA SEMIAUTOMATICA" data-proceso="10" data-cvepega = 'UNIVM  5435'>Semi-automatica</label>

   </div>

 </div>

 <div class="panel panel-default">

   <h4 class="bs-titulo"><span>Impresion</span></h4>

   <div class="panel-body">

     <div class="row" style="margin-top: 10px;">

      <div class="col-md-2">

        <div class="radio">

          <label><input type="radio" name="tipo_impresion" id="imp-flexo" name="tipo_impresion" value="3" data-maquina="FLEXOGRAFICA" data-proceso="8">Flexo</label>

        </div>

        <div class="radio">

          <label><input type="radio" name="tipo_impresion" id="imp-offset" name="tipo_impresion" value="14" data-maquina="OFFSET" data-proceso="8">Offset</label>

        </div>

        <div class="checkbox">
          <label><input type="checkbox" value="1" name="sel_color" id="sel_color">Sel. Color</label>

        </div>

      </div>



      <div class="col-md-2">

        <span class="help-block helper">Num tintas</span>

        <select name="num_tintas" class="form-control input-sm" id="num_tintas">
          <option value="0">0</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
        </select>
        
      </div>

      <div class="col-md-2">

        <span class="help-block helper">Largo</span>
        <div class="inner-addon left-addon">
          <span class="lbl-side">(1)</span>
          <input type="text" class="form-control input-sm" id="largo_tinta1" name="largo_tinta1">
        </div>

        <br>

        <span class="help-block helper">Ancho</span>
        <input type="text" class="form-control input-sm" id="ancho_tinta1" name="ancho_tinta1">

        <br>

        <span class="help-block helper">Color 1</span>
        <input type="text" class="form-control input-sm" id="color_tinta1" name="color_tinta1">

      </div>

      <div class="col-md-2">

        <span class="help-block helper">Largo</span>
        <div class="inner-addon left-addon">
          <span class="lbl-side">(2)</span>
          <input type="text" class="form-control input-sm" id="largo_tinta2" name="largo_tinta2" >
        </div>

        <br>

        <span class="help-block helper">Ancho</span>
        <input type="text" class="form-control input-sm" id="ancho_tinta2" name="ancho_tinta2" >  

        <br>

        <span class="help-block helper">Color 2</span>
        <input type="text" class="form-control input-sm" id="color_tinta2" name="color_tinta2">            

      </div>

      <div class="col-md-2">

        <span class="help-block helper">Largo</span>
        <div class="inner-addon left-addon">
          <span class="lbl-side">(3)</span>
          <input type="text" class="form-control input-sm" id="largo_tinta3" name="largo_tinta3" >
        </div>

        <br>

        <span class="help-block helper">Ancho</span>
        <input type="text" class="form-control input-sm" id="ancho_tinta3" name="ancho_tinta3" >

        <br>

        <span class="help-block helper">Color 3</span>
        <input type="text" class="form-control input-sm" id="color_tinta3" name="color_tinta3">       

      </div>

      <div class="col-md-2">

        <span class="help-block helper">Largo</span>
        <div class="inner-addon left-addon">
          <span class="lbl-side">(4)</span>
          <input type="text" class="form-control input-sm" id="largo_tinta4" name="largo_tinta4" >
        </div>

        <br>

        <span class="help-block helper">Ancho</span>
        <input type="text" class="form-control input-sm" id="ancho_tinta4" name="ancho_tinta4" >

        <br>

        <span class="help-block helper">Color 4</span>
        <input type="text" class="form-control input-sm" id="color_tinta4" name="color_tinta4">         

      </div>

    </div>

  </div>

</div>

<div class="panel panel-default">

 <h4 class="bs-titulo"><span>Empaque</span></h4>

 <div class="panel-body" style="margin-top: 10px;">

  <div class="row" style="margin-bottom: 30px;">
    <div class="col-md-3">
      <span class="help-block helper">Flejado</span>
      <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" name="flejado" id="flejado" value="1">
        </span>
        <input type="text" class="form-control" placeholder="0" name="cant_flejado" id="cant_flejado">
      </div>
    </div>
    <div class="col-md-3">
      <span class="help-block helper">Ligas</span>
      <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" name="ligas" id="ligas" value="1">
        </span>
        <input type="text" class="form-control" aria-label="..." placeholder="0" name="num_ligas" id="num_ligas">
      </div>
    </div>
    <div class="col-md-3">
      <span class="help-block helper">Corrugado</span>
      <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" name="corrugado" id="corrugado" value="1">
        </span>
        <input type="text" class="form-control" aria-label="..." placeholder="0" name="cant_xcorrugado" id="cant_xcorrugado">
      </div>
    </div>
    <div class="col-md-3">
      <span class="help-block helper">Fajilla</span>
      <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" name="fajillas" id="fajillas" value="1">
        </span>
        <input type="text" class="form-control" aria-label="..." placeholder="0" name="num_fajillas" id="num_fajillas">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <span class="help-block helper">Tarima</span>
      <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" aria-label="..." name="tarima" id="tarima" value="1">
        </span>
        <input type="text" class="form-control" aria-label="..." placeholder="0" name="cant_xtarima" id="cant_xtarima">
      </div>
    </div>
    <div class="col-md-3">
      <span class="help-block helper">Paquetes</span>
      <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" aria-label="..." name="paquetes" value="1">
        </span>
        <input type="text" class="form-control" aria-label="..." placeholder="0" name="cant_xpaquete" id="cant_xpaquete">
      </div>
    </div>
    <div class="col-md-6 helper-left">
      <label class="checkbox-inline" style="font-size: .85em; line-height: 18px;"><input type="checkbox" id="esquineros" name="esquineros" value="1">Esquineros</label>

      <label class="checkbox-inline" style="font-size: .85em; line-height: 18px;"><input type="checkbox" id="emplayado" name="emplayado" value="1">Emplayado</label>
    </div>
  </div>
</div>

</div>

<div class="row">

  <div class="col-md-12">

    <div class="panel panel-default">

      <h4 class="bs-titulo"><span>Envío</span></h4>

      <div class="panel-body">
        <div class="col-md-6">
          <label class="radio-inline"><input type="radio" id="domicilio" name="tipo_envio" value="DOMICILIO">A domicilio</label>
        </div>
        <div class="col-md-6">
          <label class="radio-inline"><input type="radio" id="cliente" name="tipo_envio" value="CLIENTE RECOGE">Cliente recoge</label>
        </div>
      </div>

    </div>

  </div>

</div>



<div class="panel panel-default">

 <h4 class="bs-titulo"><span>Notas</span></h4>

 <div class="panel-body">

   <div class="form-group">

    <textarea class="form-control input-sm" rows="2" id="notas" name="notas"></textarea>

  </div>

</div>

</div>



<div class="panel panel-default">

 <h4 class="bs-titulo"><span>Opciones</span></h4>

 <div class="panel-body">

   <button type="button" class="btn btn-default" id="btn-salir">Salir</button>

   <button type="button" class="btn btn-primary" id="btn-guardar">Guardar</button>

   <button type="button" class="btn btn-primary" id="btn-editar">Editar</button>

   <button type="button" class="btn btn-primary" id="btn-liberar">Liberar</button>

   <button type="button" class="btn btn-primary" id="btn-clonar">Clonar</button>

   <button type="button" class="btn btn-primary" id="btn-editar2">Guardar</button>

   <button type="button" class="btn btn-primary" id="btn-guardar2">Guardar</button>

 </div>

</div>

</form>


<script type="text/javascript">


  function getParameterByName(name, url) {
    if (!url) url = window.location.href;
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
    results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
  }

  $.ajax({
    type: "GET",
    url: 'buscaclientes',
    async: false,
    success: function (response) {
      $('#id_cliente').html(response);

    },
    error: function () {
      $('#id_cliente').html('Hubo un error');
    }
  });

  $.ajax({
    dataType: "json",
    url: 'selarticulo',
    async: false,
    success: function(data){
      $('select[name="articulo"]').append(data);
    }
  });

  var Tipo = getParameterByName('Tipo');

  if(Tipo == 1){

    $('#btn-guardar').show();
    $('#btn-editar').hide();
    $('#btn-editar2').hide();
    $('#btn-guardar2').hide();
    $('#btn-liberar').hide();
    $('#btn-clonar').hide();
    
  }

  if(Tipo == 2){

    $('#btn-guardar').hide();
    $('#btn-editar2').hide();
    $('#btn-guardar2').hide();

    var IdOrden = getParameterByName('ID');

    $.ajax({
      type: "POST",
      url: 'ordenproduccion',
      dataType: "json",
      data: {id_ordenproduccion: IdOrden},
      success: function (data) {

       var emision = data['fecha_emision'];
       emision = emision.split(" ");

       var requerida = data['fecha_requeridaentrega'];
       requerida = requerida.split(" ");

       $('input').attr('readonly', true);
       $('input:radio').attr('disabled', true);
       $('input:checkbox').attr('disabled', true);
       $('select').attr('disabled', true);
       $('textarea').attr('readonly', true);

       $('.num_folio').text(data['id_ordenproduccion']);
       //$('input[name="id_ordenproduccion"]').val(data['id_ordenproduccion']);
       $('input[name="id_ordenmaterial"]').val(data['id_ordenmaterial']);
       $('input[name="id_ordencompra"]').val(data['id_ordencompra']);
       $('input[name="id_cotizacion"]').val(data['id_cotizacion']);
       $('#id_cliente').selectpicker('val', data['id_cliente']);
       $('input[name="nombre_trabajo"]').val(data['nombre_trabajo']);
       $('input[name="fecha_emision"]').val(emision[0]);
       $('input[name="fecha_requeridaentrega"]').val(requerida[0]);
       $('textarea[name="notas"]').val(data['notas']);


       $('#id_cliente').selectpicker('refresh');

     }
   });

    $.ajax({
      type: "POST",
      url: 'detalleordenproduccion',
      dataType: "json",
      data: {id_ordenproduccion: IdOrden},
      success: function (response) {

        $('input[name="cant_requerida"]').val(response['cant_requerida']);
        $('input[name="med_frente"]').val(response['med_frente']);
        $('input[name="med_fondo"]').val(response['med_fondo']);
        $('input[name="med_alto"]').val(response['med_alto']);
        $('input[name="tipo_medida"][value="'+response['tipo_medida']+'"]').prop("checked",true);
        $('input[name="med_largo"]').val(response['med_largo']);
        $('input[name="med_ancho"]').val(response['med_ancho']);
        $('input[id="med_requerido"]').val(response['med_largo'] + " x " + response['med_ancho']);
        $('select[name="articulo"]>option').removeAttr("selected");
        $('select[name="articulo"]>option[value="'+response['articulo']+'"]').attr("selected", true);

        $.ajax({
          dataType: "json",
          url: 'selproducto',
          type: "POST",
          data: {Clasificacion : response['articulo']},
          success: function(data){
            $('select[name="tipo_producto"]').html('<option value="null">SELECCIONAR</option>');
            $('select[name="tipo_producto"]').append(data);

            $('select[name="tipo_producto"]>option').removeAttr("selected");
            $('select[name="tipo_producto"]>option[value="'+response['tipo_producto']+'"]').attr("selected", true);
          }
        });

        $('input[name="selector_material"][value="'+response['selector_material']+'"]').prop("checked",true);

        $.ajax({
          dataType: "json",
          url: 'tipomaterial',
          type: "POST",
          data: {'tipoMaterial' : response['selector_material']},
          success: function(data){
            $('select[name="tipo_material"]').html('<option value="null">SELECCIONAR</option>');
            $('select[name="tipo_material"]').append(data);

            $('select[name="tipo_material"]>option').removeAttr("selected");
            $('select[name="tipo_material"]>option[value="'+response['tipo_material']+'"]').attr("selected", true);

            $.ajax({
              dataType: "json",
              url: 'selmatcorrugados',
              type: "POST",
              data: {Material : response['tipo_material']},
              success: function(data){

                $('select[name="carton"]').html('<option value="null">SELECCIONAR</option>');
                $('select[name="carton"]').append(data);

                $('select[name="carton"]>option').removeAttr("selected");
                $('select[name="carton"]>option[value="'+response['carton']+'"]').attr("selected", true);

                $.ajax({
                  dataType: "json",
                  url: 'seltamcorrugados',
                  type: "POST",
                  data: {Id : response['carton']},
                  success: function(data){

                    $('select[name="tam-carton"]').html('<option value="null">SELECCIONAR</option>');
                    $('select[name="tam-carton"]').append(data);

                    $('select[name="tam-carton"]>option').removeAttr("selected");
                    $('select[name="tam-carton"]>option[value="'+response['carton']+'"]').attr("selected", true);

                  }
                });

              }
            });

          }
        });

        $('input[name="maquina_suajado"][value="'+response['maquina_suajado']+'"]').prop("checked",true);
        $('input[name="med_suaje"]').val(response['med_suaje']);
        $('input[name="med_cito"]').val(response['med_cito']);
        $('input[name="tipo_desbarbe"]').val(response['tipo_desbarbe']);
        $('input[name="tipo_pegado"][value="'+response['tipo_pegado']+'"]').prop("checked",true);
        $('input[name="predoblado"][value="'+response['predoblado']+'"]').prop("checked",true);
        $('input[name="clave_pegamento"]').val(response['clave_pegamento']);
        $('input[name="pegado_con"][value="'+response['pegado_con']+'"]').prop("checked",true);
        $('input[name="grapado"]').prop("checked",true);
        $('input[name="num_grapas"]').val(response['num_grapas']);
        $('input[name="tipo_envio"][value="'+response['tipo_envio']+'"]').prop("checked",true);
        $('input[name="tipo_entrega"][value="'+response['tipo_entrega']+'"]').prop("checked",true);
        $('input[name="maquina_ranurado"][value="'+response['maquina_ranurado']+'"]').prop("checked",true);
        $('input[name="proceso_refilado"][value="'+response['proceso_refilado']+'"]').prop("checked",true);
        $('input[name="maquina_empalme"][value="'+response['maquina_empalme']+'"]').prop("checked",true);
        $('input[name="tipo_impresion"][value="'+response['tipo_impresion']+'"]').prop("checked",true);
        $('input[name="sel_color"][value="'+response['sel_color']+'"]').prop("checked",true);
        $('select[name="num_tintas"]>option').removeAttr("selected");
        $('select[name="num_tintas"]>option[value="'+response['num_tintas']+'"]').attr("selected", true);
        $('input[name="largo_tinta1"]').val(response['largo_tinta1']);
        $('input[name="ancho_tinta1"]').val(response['ancho_tinta1']);
        $('input[name="color_tinta1"]').val(response['color_tinta1']);
        $('input[name="largo_tinta2"]').val(response['largo_tinta2']);
        $('input[name="ancho_tinta2"]').val(response['ancho_tinta2']);
        $('input[name="color_tinta2"]').val(response['color_tinta2']);
        $('input[name="largo_tinta3"]').val(response['largo_tinta3']);
        $('input[name="ancho_tinta3"]').val(response['ancho_tinta3']);
        $('input[name="color_tinta3"]').val(response['color_tinta3']);
        $('input[name="largo_tinta4"]').val(response['largo_tinta4']);
        $('input[name="ancho_tinta4"]').val(response['ancho_tinta4']);
        $('input[name="color_tinta4"]').val(response['color_tinta4']);
        $('input[name="flejado"][value="'+response['flejado']+'"]').prop("checked",true);
        $('input[name="cant_flejado"]').val(response['cant_flejado']);
        $('input[name="ligas"][value="'+response['ligas']+'"]').prop("checked",true);
        $('input[name="num_ligas"]').val(response['num_ligas']);
        $('input[name="corrugado"][value="'+response['corrugado']+'"]').prop("checked",true);
        $('input[name="cant_xcorrugado"]').val(response['cant_xcorrugado']);
        $('input[name="fajillas"][value="'+response['fajillas']+'"]').prop("checked",true);
        $('input[name="num_fajillas"]').val(response['num_fajillas']);
        $('input[name="tarima"][value="'+response['tarima']+'"]').prop("checked",true);
        $('input[name="cant_xtarima"]').val(response['cant_xtarima']);
        $('input[name="paquetes"][value="'+response['paquetes']+'"]').prop("checked",true);
        $('input[name="cant_xpaquete"]').val(response['cant_xpaquete']);
        $('input[name="cant_granel"]').val(response['cant_granel']);
        $('input[name="esquineros"][value="'+response['esquineros']+'"]').prop("checked",true);
        $('input[name="emplayado"][value="'+response['emplayado']+'"]').prop("checked",true);
        

      }
    });

}


$("#btn-salir").click(function(){
  window.location.href = "activas";      
});






$('input[type=radio]').click(function(e){

 if (e.ctrlKey) {

   $(this).prop('checked', false);

 }

});



$('select[name="tipo_material"]').change(function(){

  var value = $('select[name="tipo_material"] option:selected').val();

  var texto = $('select[name="tipo_material"] option:selected').text();

  $.ajax({
    dataType: "json",
    url: 'selmatcorrugados',
    type: "POST",
    data: {Material : texto},
    success: function(data){
      $('select[name="carton"]').html('<option value="null">SELECCIONAR</option>');
      $('select[name="carton"]').append(data);
    }
  });



  $('select[name="carton"]').change(function(){

    var id = $('select[name="carton"] option:selected').val();

    $.ajax({
      dataType: "json",
      url: 'seltamcorrugados',
      type: "POST",
      data: {Descripcion : id},
      success: function(data2){
        $('select[name="tam-carton"]').html('<option value="null">SELECCIONAR</option>');
        $('select[name="tam-carton"]').append(data2);

      }
    });


  });




})

$('select[name="articulo"]').change(function(){

  var value = $('select[name="articulo"] option:selected').data('descripcion');

  $.ajax({
    dataType: "json",
    url: 'selproducto',
    type: "POST",
    data: {Clasificacion : value},
    success: function(data){
      $('select[name="tipo_producto"]').html('<option value="null">SELECCIONAR</option>');
      $('select[name="tipo_producto"]').append(data);
    }
  });
})


$( "#btn-guardar" ).click(function() {

  var user = localStorage.user;

  var ordenProduccion = $("#OrdenProduccion").serialize() + "&id_usuario="+user+"&tipo_orden=MANUAL";

  $.ajax({

   dataType: "json",

   data: ordenProduccion,

   url: 'guardaordenproduccion',

   type:  'post',

   success: function(data){

     if(data.validacion){


       swal(

        '',

        'Se ha guardado la orden correctamente',

        'success'

        );

     }

   }

 });



});

$('input[name="selector_material"]:radio').click(function(){


  var value = $('input[name="selector_material"]:checked').val();

  $.ajax({
    dataType: "json",
    url: 'tipomaterial',
    type: "POST",
    data: {'tipoMaterial' : value},
    success: function(data){
      $('select[name="tipo_material"]').html('<option value="null">SELECCIONAR</option>');
      $('select[name="carton"]').html('<option value="null">SELECCIONAR</option>');
      $('select[name="tam-carton"]').html('<option value="null">SELECCIONAR</option>');
      $('select[name="tipo_material"]').append(data);
    }
  });

});



$('#btn-liberar').click(function(){

 var idorden = $('span[id="IdOrden"]').text();

 var trabajo = $('input[name="nombre_trabajo"]').val();


 if($('input[name="maquina_suajado"]:radio').is(':checked')){

   var idmaquina = $('input[name="maquina_suajado"]:checked').val();

   var maquina = $('input[name="maquina_suajado"]:checked').data('maquina');

   var proceso = $('input[name="maquina_suajado"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();



   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': 'SUAJADO',

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){



       }

     }

   });

 }



 if($('input[name="tipo_pegado"]:radio').is(':checked')){

   var idmaquina = $('input[name="tipo_pegado"]:checked').val();

   var maquina = $('input[name="tipo_pegado"]:checked').data('maquina');

   var proceso = $('input[name="tipo_pegado"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();

   var nombreproceso = 'PEGADO';

   if (idmaquina == 4){

     nombreproceso = 'PEGADO CAJAS'

   }

   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': nombreproceso,

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){


       }

     }

   });



 }



 if($('input[name="grapado"]:checkbox').is(':checked')){

   var idmaquina = $('input[name="grapado"]:checked').val();

   var maquina = $('input[name="grapado"]:checked').data('maquina');

   var proceso = $('input[name="grapado"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();

   var nombreproceso = 'GRAPADO';


   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': nombreproceso,

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){



       }

     }

   });



 }



 if($('input[name="maquina_ranurado"]:radio').is(':checked')){

   var idmaquina = $('input[name="maquina_ranurado"]:checked').val();

   var maquina = $('input[name="maquina_ranurado"]:checked').data('maquina');

   var proceso = $('input[name="maquina_ranurado"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();

   var nombreproceso = 'RANURADO';


   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': nombreproceso,

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){



       }

     }

   });



 }



 if($('input[name="proceso_refilado"]:radio').is(':checked')){

   var idmaquina = $('input[name="proceso_refilado"]:checked').val();

   var maquina = $('input[name="proceso_refilado"]:checked').data('maquina');

   var proceso = $('input[name="proceso_refilado"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();


   if(proceso == 5){

     var nombreproceso = 'RAYADO';

   }

   
   if(proceso == 6){

     var nombreproceso = 'REFILADO';

   }


   if(proceso == 7){

     var nombreproceso = 'REFILADO RAYADO';

   }                                            



   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': nombreproceso,

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){



       }

     }

   });



 }



 if($('input[name="maquina_empalme"]:radio').is(':checked')){

   var idmaquina = $('input[name="maquina_empalme"]:checked').val();

   var maquina = $('input[name="maquina_empalme"]:checked').data('maquina');

   var proceso = $('input[name="maquina_empalme"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();



   var nombreproceso = 'EMPALME';



   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': nombreproceso,

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){



       }

     }

   });



 }



 if($('input[name="tipo_impresion"]:radio').is(':checked')){

   var idmaquina = $('input[name="tipo_impresion"]:checked').val();

   var maquina = $('input[name="tipo_impresion"]:checked').data('maquina');

   var proceso = $('input[name="tipo_impresion"]:checked').data('proceso');

   var requerida = $('input[name="cant_requerida"]').val();



   if(idmaquina == 3){

     var nombreproceso = 'FLEXOGRAFICA';

   }



   if(idmaquina == 14){

     var nombreproceso = 'MAQ OFFSET';

   }             



   $.ajax({

     dataType: "json",

     data: {

       'id_orden': idorden,

       'nombre_trabajo': trabajo,

       'id_maquina': idmaquina,

       'nombre_maquina': maquina,

       'id_proceso': proceso,

       'nombre_proceso': nombreproceso,

       'cant_requerida': requerida,

     },

     url: 'liberaordenproduccion',

     type:  'post',

     success: function(data){

       if(data.validacion){



       }

     }

   });                                         



 }


 swal(
  '¡Correcto!',
  'Se ha liberado la orden',
  'success'
  );
 orden=  $('.num_folio').text();
 generarMembrete(orden);  


});

$( 'input[id="med_largo"]' ).keyup(function() {
  $( 'input[id="med_requerido"]' ).val($( 'input[id="med_largo"]' ).val()+"x"+$( 'input[id="med_ancho"]' ).val())
});

$( 'input[id="med_ancho"]' ).keyup(function() {
  $( 'input[id="med_requerido"]' ).val($( 'input[id="med_largo"]' ).val()+"x"+$( 'input[id="med_ancho"]' ).val())
});

$("#btn-editar").click(function(){

  $(this).hide();
  $('input').attr('readonly', false);
  $('input:radio').attr('disabled', false);
  $('input:checkbox').attr('disabled', false);
  $('select').attr('disabled', false);
  $('textarea').attr('readonly', false);
  $('#btn-liberar').hide();
  $('#btn-clonar').hide();
  $('#btn-editar2').show();

});

$("#btn-editar2").click(function(){

  var IdOrden = getParameterByName('ID');
  var ordenProduccion = $("#OrdenProduccion").serialize();

  $.ajax({

   dataType: "json",
   data: ordenProduccion,
   url: 'updateorden',
   type:  'post',
   success: function(data){
     if(data.validacion){
       swal(

        '',
        'Se ha guardado la orden correctamente',
        'success'

        );
     }

   }

 });
  
  
});

$("#btn-salir").click(function(){
  window.location.href = "activas";      
});



$('input[id="mcaja"]').on('click', function() { 

  if( $('input[id="mcaja"]').prop("checked") == true){

    var frente = $('input[name="med_frente"]').val();
    var fondo = $('input[name ="med_fondo"]').val();
    var alto = $('input[id="med_alto"]').val();

    if(frente != "" && fondo != "" && alto != ""){

      var largo = (2*frente) + (2*fondo) + 4;
      var ancho = alto * fondo;

      $('input[id="med_largo"]').val(largo).attr('readonly', true);

      $('input[id="med_ancho"]').val(ancho).attr('readonly', true);

      $('input[id="med_requerido"]').val(largo + 'x' + ancho);  
      
    }else{

     alert("Faltan datos de (M. Final)");
     return false;

   }
   

 }else{

  alert("No Esta checkado");

}
});

$('input[id="mcarton"]').on('click', function() { 

  if( $('input[id="mcarton"]').prop("checked") == true){

      $('input[id="med_largo"]').val("").attr('readonly', false);

      $('input[id="med_ancho"]').val("").attr('readonly', false);

      $('input[id="med_requerido"]').val("");
   

 }
});

$('input[name="tipo_pegado"]').on('click', function() { 

  $('input[name = clave_pegamento]').val($('input:radio[name = tipo_pegado]:checked').data('cvepega'));

});

$('input[name="maquina_empalme"]').on('click', function() { 

  $('input[name = clave_pegamento]').val($('input:radio[name = maquina_empalme]:checked').data('cvepega'));

});



function generarMembrete()
{
  //$.post('../../application/models/generarMarbete.php', {orden:orden});
  window.open("../../application/models/generarMarbete.php?orden=" + orden,'_blank');
}

</script>